// Pre-defined grocery items that users can select from
export interface GroceryItemTemplate {
    id: string;
    name: string;
    category: string;
    default_unit: string;
    estimated_price_per_unit: number; // MAD
}

export const groceryItemTemplates: GroceryItemTemplate[] = [
    // === PROTEINS ===
    { id: "chicken_breast", name: "Chicken breast", category: "protein", default_unit: "kg", estimated_price_per_unit: 55 },
    { id: "chicken_thighs", name: "Chicken thighs", category: "protein", default_unit: "kg", estimated_price_per_unit: 45 },
    { id: "whole_chicken", name: "Whole chicken", category: "protein", default_unit: "kg", estimated_price_per_unit: 38 },
    { id: "ground_beef", name: "Ground beef", category: "protein", default_unit: "kg", estimated_price_per_unit: 80 },
    { id: "beef_steak", name: "Beef steak", category: "protein", default_unit: "kg", estimated_price_per_unit: 120 },
    { id: "lamb_chops", name: "Lamb chops", category: "protein", default_unit: "kg", estimated_price_per_unit: 140 },
    { id: "ground_lamb", name: "Ground lamb", category: "protein", default_unit: "kg", estimated_price_per_unit: 90 },
    { id: "turkey_breast", name: "Turkey breast", category: "protein", default_unit: "kg", estimated_price_per_unit: 65 },
    { id: "ground_turkey", name: "Ground turkey", category: "protein", default_unit: "kg", estimated_price_per_unit: 60 },
    { id: "eggs", name: "Eggs", category: "protein", default_unit: "pcs", estimated_price_per_unit: 1.5 },
    { id: "sardines_fresh", name: "Sardines (fresh)", category: "protein", default_unit: "kg", estimated_price_per_unit: 25 },
    { id: "sardines_canned", name: "Sardines (canned)", category: "protein", default_unit: "pcs", estimated_price_per_unit: 8 },
    { id: "salmon_fillet", name: "Salmon fillet", category: "protein", default_unit: "kg", estimated_price_per_unit: 180 },
    { id: "shrimp", name: "Shrimp", category: "protein", default_unit: "kg", estimated_price_per_unit: 120 },
    { id: "tuna_canned", name: "Tuna (canned)", category: "protein", default_unit: "pcs", estimated_price_per_unit: 15 },
    { id: "white_fish_cod_tilapia", name: "White fish (cod/tilapia)", category: "protein", default_unit: "kg", estimated_price_per_unit: 80 },
    { id: "prawns", name: "Prawns", category: "protein", default_unit: "kg", estimated_price_per_unit: 150 },
    { id: "merguez_sausages", name: "Merguez sausages", category: "protein", default_unit: "kg", estimated_price_per_unit: 70 },

    // === CARBS & GRAINS ===
    { id: "white_rice", name: "White rice", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { id: "brown_rice", name: "Brown rice", category: "carbs", default_unit: "kg", estimated_price_per_unit: 18 },
    { id: "basmati_rice", name: "Basmati rice", category: "carbs", default_unit: "kg", estimated_price_per_unit: 22 },
    { id: "potatoes", name: "Potatoes", category: "carbs", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "sweet_potatoes", name: "Sweet potatoes", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { id: "quinoa", name: "Quinoa", category: "carbs", default_unit: "kg", estimated_price_per_unit: 65 },
    { id: "couscous", name: "Couscous", category: "carbs", default_unit: "kg", estimated_price_per_unit: 20 },
    { id: "whole_wheat_pasta", name: "Whole wheat pasta", category: "carbs", default_unit: "kg", estimated_price_per_unit: 25 },
    { id: "regular_pasta_spaghetti", name: "Regular pasta (spaghetti)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "pasta_penne", name: "Pasta (penne)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "pasta_macaroni", name: "Pasta (macaroni)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 14 },
    { id: "vermicelli", name: "Vermicelli", category: "carbs", default_unit: "kg", estimated_price_per_unit: 16 },
    { id: "oats", name: "Oats", category: "carbs", default_unit: "kg", estimated_price_per_unit: 30 },
    { id: "oat_flakes", name: "Oat flakes", category: "carbs", default_unit: "kg", estimated_price_per_unit: 35 },
    { id: "whole_wheat_bread", name: "Whole wheat bread", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 8 },
    { id: "white_bread", name: "White bread", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 5 },
    { id: "khobz_moroccan_bread", name: "Khobz (Moroccan bread)", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 2 },
    { id: "whole_wheat_tortillas", name: "Whole wheat tortillas", category: "carbs", default_unit: "pack", estimated_price_per_unit: 18 },
    { id: "corn_tortillas", name: "Corn tortillas", category: "carbs", default_unit: "pack", estimated_price_per_unit: 12 },
    { id: "rice_noodles", name: "Rice noodles", category: "carbs", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "lentils_green", name: "Lentils (green)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 18 },
    { id: "lentils_red", name: "Lentils (red)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 20 },
    { id: "chickpeas_dried", name: "Chickpeas (dried)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 20 },
    { id: "chickpeas_canned", name: "Chickpeas (canned)", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 10 },
    { id: "black_beans_canned", name: "Black beans (canned)", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 12 },
    { id: "white_beans_dried", name: "White beans (dried)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 22 },
    { id: "fava_beans_dried", name: "Fava beans (dried)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "wheat_flour", name: "Wheat flour", category: "carbs", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "whole_wheat_flour", name: "Whole wheat flour", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { id: "semolina_fine", name: "Semolina (fine)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "semolina_coarse", name: "Semolina (coarse)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "cornmeal", name: "Cornmeal", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { id: "bulgur_wheat", name: "Bulgur wheat", category: "carbs", default_unit: "kg", estimated_price_per_unit: 18 },
    { id: "crackers", name: "Crackers", category: "carbs", default_unit: "pack", estimated_price_per_unit: 15 },

    // === VEGETABLES ===
    { id: "tomatoes", name: "Tomatoes", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "cherry_tomatoes", name: "Cherry tomatoes", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "cucumber", name: "Cucumber", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "bell_peppers_red", name: "Bell peppers (red)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 25 },
    { id: "bell_peppers_green", name: "Bell peppers (green)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 18 },
    { id: "bell_peppers_yellow", name: "Bell peppers (yellow)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 25 },
    { id: "onions_yellow", name: "Onions (yellow)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 6 },
    { id: "onions_red", name: "Onions (red)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "garlic", name: "Garlic", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 2 },
    { id: "shallots", name: "Shallots", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "carrots", name: "Carrots", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "broccoli", name: "Broccoli", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 20 },
    { id: "cauliflower", name: "Cauliflower", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 12 },
    { id: "zucchini", name: "Zucchini", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 12 },
    { id: "eggplant", name: "Eggplant", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "spinach", name: "Spinach", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 5 },
    { id: "lettuce_romaine", name: "Lettuce (romaine)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 6 },
    { id: "lettuce_iceberg", name: "Lettuce (iceberg)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { id: "mixed_salad_greens", name: "Mixed salad greens", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "green_beans", name: "Green beans", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "mushrooms", name: "Mushrooms", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 18 },
    { id: "celery", name: "Celery", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 8 },
    { id: "cabbage_white", name: "Cabbage (white)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { id: "cabbage_red", name: "Cabbage (red)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 10 },
    { id: "corn_fresh", name: "Corn (fresh)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 3 },
    { id: "peas_frozen", name: "Peas (frozen)", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 12 },
    { id: "mixed_vegetables_frozen", name: "Mixed vegetables (frozen)", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "leeks", name: "Leeks", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 10 },
    { id: "turnips", name: "Turnips", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "beetroot", name: "Beetroot", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "radishes", name: "Radishes", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 5 },
    { id: "artichokes", name: "Artichokes", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { id: "asparagus", name: "Asparagus", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 25 },
    { id: "pumpkin", name: "Pumpkin", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { id: "squash", name: "Squash", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "green_peas_fresh", name: "Green peas (fresh)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 18 },
    { id: "broad_beans_fresh", name: "Broad beans (fresh)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "fennel", name: "Fennel", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { id: "spring_onions", name: "Spring onions", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 3 },
    { id: "chili_peppers", name: "Chili peppers", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 5 },
    { id: "jalape_os", name: "Jalapeños", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 8 },

    // === FRUITS ===
    { id: "apples", name: "Apples", category: "fruits", default_unit: "kg", estimated_price_per_unit: 20 },
    { id: "bananas", name: "Bananas", category: "fruits", default_unit: "kg", estimated_price_per_unit: 12 },
    { id: "oranges", name: "Oranges", category: "fruits", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "lemons", name: "Lemons", category: "fruits", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "limes", name: "Limes", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 2 },
    { id: "strawberries", name: "Strawberries", category: "fruits", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "blueberries", name: "Blueberries", category: "fruits", default_unit: "pack", estimated_price_per_unit: 35 },
    { id: "grapes_green", name: "Grapes (green)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 30 },
    { id: "grapes_red", name: "Grapes (red)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 32 },
    { id: "watermelon", name: "Watermelon", category: "fruits", default_unit: "kg", estimated_price_per_unit: 6 },
    { id: "melon", name: "Melon", category: "fruits", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "pineapple", name: "Pineapple", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 20 },
    { id: "avocado", name: "Avocado", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 12 },
    { id: "dates_fresh", name: "Dates (fresh)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 50 },
    { id: "dates_dried", name: "Dates (dried)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 40 },
    { id: "dried_apricots", name: "Dried apricots", category: "fruits", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "raisins", name: "Raisins", category: "fruits", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "dried_figs", name: "Dried figs", category: "fruits", default_unit: "pack", estimated_price_per_unit: 30 },
    { id: "prunes", name: "Prunes", category: "fruits", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "mangoes", name: "Mangoes", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 15 },
    { id: "pears", name: "Pears", category: "fruits", default_unit: "kg", estimated_price_per_unit: 25 },
    { id: "peaches", name: "Peaches", category: "fruits", default_unit: "kg", estimated_price_per_unit: 22 },
    { id: "plums", name: "Plums", category: "fruits", default_unit: "kg", estimated_price_per_unit: 20 },
    { id: "kiwis", name: "Kiwis", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 5 },
    { id: "pomegranate", name: "Pomegranate", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 10 },

    // === DAIRY ===
    { id: "greek_yogurt", name: "Greek yogurt", category: "dairy", default_unit: "kg", estimated_price_per_unit: 45 },
    { id: "plain_yogurt_danone", name: "Plain yogurt (Danone)", category: "dairy", default_unit: "pack", estimated_price_per_unit: 12 },
    { id: "lben", name: "Lben", category: "dairy", default_unit: "L", estimated_price_per_unit: 10 },
    { id: "raib", name: "Raib", category: "dairy", default_unit: "L", estimated_price_per_unit: 12 },
    { id: "cottage_cheese", name: "Cottage cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "feta_cheese", name: "Feta cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 30 },
    { id: "mozzarella", name: "Mozzarella", category: "dairy", default_unit: "pack", estimated_price_per_unit: 35 },
    { id: "cheddar_cheese", name: "Cheddar cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 40 },
    { id: "parmesan", name: "Parmesan", category: "dairy", default_unit: "pack", estimated_price_per_unit: 50 },
    { id: "jben_moroccan_cheese", name: "Jben (Moroccan cheese)", category: "dairy", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "cream_cheese", name: "Cream cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "milk_whole", name: "Milk (whole)", category: "dairy", default_unit: "L", estimated_price_per_unit: 8 },
    { id: "milk_skim", name: "Milk (skim)", category: "dairy", default_unit: "L", estimated_price_per_unit: 9 },
    { id: "butter", name: "Butter", category: "dairy", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "smen_moroccan_butter", name: "Smen (Moroccan butter)", category: "dairy", default_unit: "jar", estimated_price_per_unit: 40 },
    { id: "cream_cooking", name: "Cream (cooking)", category: "dairy", default_unit: "pack", estimated_price_per_unit: 12 },
    { id: "sour_cream", name: "Sour cream", category: "dairy", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "whipping_cream", name: "Whipping cream", category: "dairy", default_unit: "pack", estimated_price_per_unit: 18 },

    // === NUTS & FATS ===
    { id: "olive_oil", name: "Olive oil", category: "fats", default_unit: "L", estimated_price_per_unit: 80 },
    { id: "argan_oil", name: "Argan oil", category: "fats", default_unit: "bottle", estimated_price_per_unit: 150 },
    { id: "vegetable_oil", name: "Vegetable oil", category: "fats", default_unit: "L", estimated_price_per_unit: 18 },
    { id: "coconut_oil", name: "Coconut oil", category: "fats", default_unit: "jar", estimated_price_per_unit: 60 },
    { id: "almonds", name: "Almonds", category: "fats", default_unit: "kg", estimated_price_per_unit: 120 },
    { id: "walnuts", name: "Walnuts", category: "fats", default_unit: "kg", estimated_price_per_unit: 140 },
    { id: "peanuts_raw", name: "Peanuts (raw)", category: "fats", default_unit: "kg", estimated_price_per_unit: 40 },
    { id: "peanuts_roasted", name: "Peanuts (roasted)", category: "fats", default_unit: "kg", estimated_price_per_unit: 50 },
    { id: "cashews", name: "Cashews", category: "fats", default_unit: "kg", estimated_price_per_unit: 160 },
    { id: "pistachios", name: "Pistachios", category: "fats", default_unit: "kg", estimated_price_per_unit: 180 },
    { id: "hazelnuts", name: "Hazelnuts", category: "fats", default_unit: "kg", estimated_price_per_unit: 130 },
    { id: "pine_nuts", name: "Pine nuts", category: "fats", default_unit: "pack", estimated_price_per_unit: 50 },
    { id: "peanut_butter", name: "Peanut butter", category: "fats", default_unit: "jar", estimated_price_per_unit: 45 },
    { id: "almond_butter", name: "Almond butter", category: "fats", default_unit: "jar", estimated_price_per_unit: 80 },
    { id: "tahini", name: "Tahini", category: "fats", default_unit: "jar", estimated_price_per_unit: 40 },
    { id: "chia_seeds", name: "Chia seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 50 },
    { id: "flax_seeds", name: "Flax seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 30 },
    { id: "sunflower_seeds", name: "Sunflower seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "pumpkin_seeds", name: "Pumpkin seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 35 },
    { id: "sesame_seeds", name: "Sesame seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 15 },

    // === CONDIMENTS & SAUCES ===
    { id: "soy_sauce", name: "Soy sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 20 },
    { id: "fish_sauce", name: "Fish sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 25 },
    { id: "sriracha", name: "Sriracha", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 30 },
    { id: "harissa", name: "Harissa", category: "condiments", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "teriyaki_sauce", name: "Teriyaki sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 35 },
    { id: "bbq_sauce", name: "BBQ sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 30 },
    { id: "honey", name: "Honey", category: "condiments", default_unit: "jar", estimated_price_per_unit: 50 },
    { id: "maple_syrup", name: "Maple syrup", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 80 },
    { id: "mustard", name: "Mustard", category: "condiments", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "dijon_mustard", name: "Dijon mustard", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { id: "mayonnaise", name: "Mayonnaise", category: "condiments", default_unit: "jar", estimated_price_per_unit: 20 },
    { id: "ketchup", name: "Ketchup", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 15 },
    { id: "tomato_paste", name: "Tomato paste", category: "condiments", default_unit: "can", estimated_price_per_unit: 8 },
    { id: "tomato_sauce", name: "Tomato sauce", category: "condiments", default_unit: "can", estimated_price_per_unit: 12 },
    { id: "canned_tomatoes_whole", name: "Canned tomatoes (whole)", category: "condiments", default_unit: "can", estimated_price_per_unit: 10 },
    { id: "canned_tomatoes_diced", name: "Canned tomatoes (diced)", category: "condiments", default_unit: "can", estimated_price_per_unit: 12 },
    { id: "marinara_sauce", name: "Marinara sauce", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { id: "salsa", name: "Salsa", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { id: "hummus", name: "Hummus", category: "condiments", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "vinegar_balsamic", name: "Vinegar (balsamic)", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 35 },
    { id: "vinegar_apple_cider", name: "Vinegar (apple cider)", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 25 },
    { id: "vinegar_white", name: "Vinegar (white)", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 10 },
    { id: "coconut_milk", name: "Coconut milk", category: "condiments", default_unit: "can", estimated_price_per_unit: 18 },
    { id: "olives_green", name: "Olives (green)", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { id: "olives_black", name: "Olives (black)", category: "condiments", default_unit: "jar", estimated_price_per_unit: 28 },
    { id: "pickles", name: "Pickles", category: "condiments", default_unit: "jar", estimated_price_per_unit: 20 },
    { id: "capers", name: "Capers", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },

    // === HERBS & SPICES ===
    { id: "fresh_ginger", name: "Fresh ginger", category: "herbs", default_unit: "pcs", estimated_price_per_unit: 5 },
    { id: "fresh_cilantro", name: "Fresh cilantro", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 3 },
    { id: "fresh_parsley", name: "Fresh parsley", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 3 },
    { id: "fresh_basil", name: "Fresh basil", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { id: "fresh_mint", name: "Fresh mint", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 3 },
    { id: "fresh_rosemary", name: "Fresh rosemary", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { id: "fresh_thyme", name: "Fresh thyme", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { id: "fresh_dill", name: "Fresh dill", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { id: "cumin_ground", name: "Cumin (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { id: "cumin_seeds", name: "Cumin (seeds)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "paprika", name: "Paprika", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { id: "paprika_smoked", name: "Paprika (smoked)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 18 },
    { id: "chili_powder", name: "Chili powder", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { id: "cayenne_pepper", name: "Cayenne pepper", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "turmeric", name: "Turmeric", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "cinnamon_ground", name: "Cinnamon (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { id: "cinnamon_sticks", name: "Cinnamon sticks", category: "herbs", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "oregano_dried", name: "Oregano (dried)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 10 },
    { id: "mixed_herbs", name: "Mixed herbs", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "curry_powder", name: "Curry powder", category: "herbs", default_unit: "jar", estimated_price_per_unit: 18 },
    { id: "garam_masala", name: "Garam masala", category: "herbs", default_unit: "jar", estimated_price_per_unit: 25 },
    { id: "ras_el_hanout", name: "Ras el hanout", category: "herbs", default_unit: "jar", estimated_price_per_unit: 20 },
    { id: "saffron", name: "Saffron", category: "herbs", default_unit: "pack", estimated_price_per_unit: 60 },
    { id: "black_pepper_ground", name: "Black pepper (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "black_pepper_whole", name: "Black pepper (whole)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 18 },
    { id: "salt_table", name: "Salt (table)", category: "herbs", default_unit: "pack", estimated_price_per_unit: 5 },
    { id: "salt_sea", name: "Salt (sea)", category: "herbs", default_unit: "pack", estimated_price_per_unit: 8 },
    { id: "bay_leaves", name: "Bay leaves", category: "herbs", default_unit: "pack", estimated_price_per_unit: 10 },
    { id: "coriander_ground", name: "Coriander (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { id: "cardamom", name: "Cardamom", category: "herbs", default_unit: "pack", estimated_price_per_unit: 35 },
    { id: "nutmeg", name: "Nutmeg", category: "herbs", default_unit: "pcs", estimated_price_per_unit: 5 },
    { id: "cloves", name: "Cloves", category: "herbs", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "star_anise", name: "Star anise", category: "herbs", default_unit: "pack", estimated_price_per_unit: 20 },

    // === BEVERAGES ===
    { id: "green_tea", name: "Green tea", category: "beverages", default_unit: "box", estimated_price_per_unit: 25 },
    { id: "moroccan_mint_tea", name: "Moroccan mint tea", category: "beverages", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "black_tea", name: "Black tea", category: "beverages", default_unit: "box", estimated_price_per_unit: 20 },
    { id: "coffee_ground", name: "Coffee (ground)", category: "beverages", default_unit: "pack", estimated_price_per_unit: 50 },
    { id: "coffee_instant", name: "Coffee (instant)", category: "beverages", default_unit: "jar", estimated_price_per_unit: 40 },
    { id: "coffee_beans", name: "Coffee (beans)", category: "beverages", default_unit: "kg", estimated_price_per_unit: 80 },
    { id: "sparkling_water", name: "Sparkling water", category: "beverages", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "mineral_water_5l", name: "Mineral water (5L)", category: "beverages", default_unit: "bottle", estimated_price_per_unit: 10 },
    { id: "orange_juice", name: "Orange juice", category: "beverages", default_unit: "L", estimated_price_per_unit: 20 },
    { id: "apple_juice", name: "Apple juice", category: "beverages", default_unit: "L", estimated_price_per_unit: 18 },

    // === SNACKS ===
    { id: "protein_bars", name: "Protein bars", category: "snacks", default_unit: "box", estimated_price_per_unit: 80 },
    { id: "dark_chocolate_70", name: "Dark chocolate (70%+)", category: "snacks", default_unit: "bar", estimated_price_per_unit: 25 },
    { id: "rice_cakes", name: "Rice cakes", category: "snacks", default_unit: "pack", estimated_price_per_unit: 18 },
    { id: "trail_mix", name: "Trail mix", category: "snacks", default_unit: "pack", estimated_price_per_unit: 35 },
    { id: "popcorn_kernels", name: "Popcorn kernels", category: "snacks", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "granola", name: "Granola", category: "snacks", default_unit: "pack", estimated_price_per_unit: 40 },
    { id: "energy_balls", name: "Energy balls", category: "snacks", default_unit: "pack", estimated_price_per_unit: 30 },

    // === BAKING ===
    { id: "baking_powder", name: "Baking powder", category: "baking", default_unit: "pack", estimated_price_per_unit: 8 },
    { id: "baking_soda", name: "Baking soda", category: "baking", default_unit: "pack", estimated_price_per_unit: 5 },
    { id: "yeast_dry", name: "Yeast (dry)", category: "baking", default_unit: "pack", estimated_price_per_unit: 6 },
    { id: "yeast_fresh", name: "Yeast (fresh)", category: "baking", default_unit: "pack", estimated_price_per_unit: 3 },
    { id: "vanilla_extract", name: "Vanilla extract", category: "baking", default_unit: "bottle", estimated_price_per_unit: 25 },
    { id: "cocoa_powder", name: "Cocoa powder", category: "baking", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "sugar_white", name: "Sugar (white)", category: "baking", default_unit: "kg", estimated_price_per_unit: 10 },
    { id: "sugar_brown", name: "Sugar (brown)", category: "baking", default_unit: "kg", estimated_price_per_unit: 15 },
    { id: "powdered_sugar", name: "Powdered sugar", category: "baking", default_unit: "pack", estimated_price_per_unit: 12 },
    { id: "chocolate_chips", name: "Chocolate chips", category: "baking", default_unit: "pack", estimated_price_per_unit: 30 },
    { id: "almond_flour", name: "Almond flour", category: "baking", default_unit: "pack", estimated_price_per_unit: 45 },
    { id: "coconut_flour", name: "Coconut flour", category: "baking", default_unit: "pack", estimated_price_per_unit: 40 },

    // === CLEANING PRODUCTS ===
    { id: "dish_soap", name: "Dish soap", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 15 },
    { id: "dishwasher_tablets", name: "Dishwasher tablets", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 50 },
    { id: "laundry_detergent_liquid", name: "Laundry detergent (liquid)", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 45 },
    { id: "laundry_detergent_powder", name: "Laundry detergent (powder)", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 40 },
    { id: "fabric_softener", name: "Fabric softener", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 30 },
    { id: "bleach_javel", name: "Bleach (Javel)", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 12 },
    { id: "all_purpose_cleaner", name: "All-purpose cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 20 },
    { id: "glass_cleaner", name: "Glass cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 18 },
    { id: "floor_cleaner", name: "Floor cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 25 },
    { id: "toilet_cleaner", name: "Toilet cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 18 },
    { id: "sponges", name: "Sponges", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 10 },
    { id: "steel_wool", name: "Steel wool", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 8 },
    { id: "trash_bags_large", name: "Trash bags (large)", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "trash_bags_small", name: "Trash bags (small)", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "paper_towels", name: "Paper towels", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "toilet_paper", name: "Toilet paper", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 30 },
    { id: "tissues", name: "Tissues", category: "cleaning", default_unit: "box", estimated_price_per_unit: 15 },
    { id: "hand_soap", name: "Hand soap", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 18 },
    { id: "hand_sanitizer", name: "Hand sanitizer", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 25 },
    { id: "aluminum_foil", name: "Aluminum foil", category: "cleaning", default_unit: "roll", estimated_price_per_unit: 20 },
    { id: "plastic_wrap", name: "Plastic wrap", category: "cleaning", default_unit: "roll", estimated_price_per_unit: 15 },
    { id: "ziplock_bags", name: "Ziplock bags", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 18 },
    { id: "broom", name: "Broom", category: "cleaning", default_unit: "pcs", estimated_price_per_unit: 35 },
    { id: "mop", name: "Mop", category: "cleaning", default_unit: "pcs", estimated_price_per_unit: 50 },
    { id: "dustpan", name: "Dustpan", category: "cleaning", default_unit: "pcs", estimated_price_per_unit: 20 },

    // === PERSONAL CARE ===
    { id: "shampoo", name: "Shampoo", category: "personal", default_unit: "bottle", estimated_price_per_unit: 35 },
    { id: "conditioner", name: "Conditioner", category: "personal", default_unit: "bottle", estimated_price_per_unit: 40 },
    { id: "body_wash", name: "Body wash", category: "personal", default_unit: "bottle", estimated_price_per_unit: 30 },
    { id: "soap_bars", name: "Soap bars", category: "personal", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "toothpaste", name: "Toothpaste", category: "personal", default_unit: "tube", estimated_price_per_unit: 20 },
    { id: "toothbrush", name: "Toothbrush", category: "personal", default_unit: "pcs", estimated_price_per_unit: 15 },
    { id: "deodorant", name: "Deodorant", category: "personal", default_unit: "pcs", estimated_price_per_unit: 30 },
    { id: "razor_blades", name: "Razor blades", category: "personal", default_unit: "pack", estimated_price_per_unit: 40 },
    { id: "shaving_cream", name: "Shaving cream", category: "personal", default_unit: "can", estimated_price_per_unit: 35 },
    { id: "cotton_pads", name: "Cotton pads", category: "personal", default_unit: "pack", estimated_price_per_unit: 15 },
    { id: "cotton_swabs", name: "Cotton swabs", category: "personal", default_unit: "pack", estimated_price_per_unit: 10 },
    { id: "lotion", name: "Lotion", category: "personal", default_unit: "bottle", estimated_price_per_unit: 40 },
    { id: "sunscreen", name: "Sunscreen", category: "personal", default_unit: "bottle", estimated_price_per_unit: 60 },

    // === BABY CARE ===
    { id: "diapers", name: "Diapers", category: "baby", default_unit: "pack", estimated_price_per_unit: 80 },
    { id: "baby_wipes", name: "Baby wipes", category: "baby", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "baby_formula", name: "Baby formula", category: "baby", default_unit: "can", estimated_price_per_unit: 150 },
    { id: "baby_food", name: "Baby food", category: "baby", default_unit: "jar", estimated_price_per_unit: 15 },
    { id: "baby_shampoo", name: "Baby shampoo", category: "baby", default_unit: "bottle", estimated_price_per_unit: 40 },

    // === PET CARE ===
    { id: "cat_food_dry", name: "Cat food (dry)", category: "pets", default_unit: "kg", estimated_price_per_unit: 50 },
    { id: "cat_food_wet", name: "Cat food (wet)", category: "pets", default_unit: "can", estimated_price_per_unit: 10 },
    { id: "cat_litter", name: "Cat litter", category: "pets", default_unit: "kg", estimated_price_per_unit: 25 },
    { id: "dog_food_dry", name: "Dog food (dry)", category: "pets", default_unit: "kg", estimated_price_per_unit: 40 },
    { id: "dog_food_wet", name: "Dog food (wet)", category: "pets", default_unit: "can", estimated_price_per_unit: 15 },

    // === OTHER ===
    { id: "bottled_water_pack", name: "Bottled water (pack)", category: "other", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "ice_cubes", name: "Ice cubes", category: "other", default_unit: "pack", estimated_price_per_unit: 10 },
    { id: "candles", name: "Candles", category: "other", default_unit: "pack", estimated_price_per_unit: 20 },
    { id: "matches", name: "Matches", category: "other", default_unit: "box", estimated_price_per_unit: 2 },
    { id: "batteries_aa", name: "Batteries (AA)", category: "other", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "batteries_aaa", name: "Batteries (AAA)", category: "other", default_unit: "pack", estimated_price_per_unit: 25 },
    { id: "light_bulbs", name: "Light bulbs", category: "other", default_unit: "pcs", estimated_price_per_unit: 15 },
];

// Get items by category
export function getGroceryItemsByCategory(): Record<string, GroceryItemTemplate[]> {
    return groceryItemTemplates.reduce((acc, item) => {
        if (!acc[item.category]) {
            acc[item.category] = [];
        }
        acc[item.category].push(item);
        return acc;
    }, {} as Record<string, GroceryItemTemplate[]>);
}

// Search items
export function searchGroceryItems(query: string): GroceryItemTemplate[] {
    const lower = query.toLowerCase();
    return groceryItemTemplates.filter(item =>
        item.name.toLowerCase().includes(lower) ||
        item.category.toLowerCase().includes(lower)
    );
}

// Category icons
export const categoryIcons: Record<string, string> = {
    protein: "🥩",
    carbs: "🍚",
    vegetables: "🥬",
    fruits: "🍎",
    dairy: "🧀",
    fats: "🥜",
    condiments: "🫙",
    herbs: "🌿",
    beverages: "🍵",
    snacks: "🍫",
    baking: "🧁",
    cleaning: "🧹",
    personal: "🧴",
    baby: "👶",
    pets: "🐾",
    other: "📦"
};

// Category display names
export const categoryNames: Record<string, string> = {
    protein: "Proteins & Meat",
    carbs: "Carbs & Grains",
    vegetables: "Vegetables",
    fruits: "Fruits",
    dairy: "Dairy",
    fats: "Nuts & Oils",
    condiments: "Condiments & Sauces",
    herbs: "Herbs & Spices",
    beverages: "Beverages",
    snacks: "Snacks",
    baking: "Baking",
    cleaning: "Cleaning Products",
    personal: "Personal Care",
    baby: "Baby Care",
    pets: "Pet Care",
    other: "Other"
};
