// Pre-defined grocery items that users can select from
export interface GroceryItemTemplate {
    name: string;
    category: string;
    default_unit: string;
    estimated_price_per_unit: number; // MAD
}

export const groceryItemTemplates: GroceryItemTemplate[] = [
    // === PROTEINS ===
    { name: "Chicken breast", category: "protein", default_unit: "kg", estimated_price_per_unit: 55 },
    { name: "Chicken thighs", category: "protein", default_unit: "kg", estimated_price_per_unit: 45 },
    { name: "Whole chicken", category: "protein", default_unit: "kg", estimated_price_per_unit: 38 },
    { name: "Ground beef", category: "protein", default_unit: "kg", estimated_price_per_unit: 80 },
    { name: "Beef steak", category: "protein", default_unit: "kg", estimated_price_per_unit: 120 },
    { name: "Lamb chops", category: "protein", default_unit: "kg", estimated_price_per_unit: 140 },
    { name: "Ground lamb", category: "protein", default_unit: "kg", estimated_price_per_unit: 90 },
    { name: "Turkey breast", category: "protein", default_unit: "kg", estimated_price_per_unit: 65 },
    { name: "Ground turkey", category: "protein", default_unit: "kg", estimated_price_per_unit: 60 },
    { name: "Eggs", category: "protein", default_unit: "pcs", estimated_price_per_unit: 1.5 },
    { name: "Sardines (fresh)", category: "protein", default_unit: "kg", estimated_price_per_unit: 25 },
    { name: "Sardines (canned)", category: "protein", default_unit: "pcs", estimated_price_per_unit: 8 },
    { name: "Salmon fillet", category: "protein", default_unit: "kg", estimated_price_per_unit: 180 },
    { name: "Shrimp", category: "protein", default_unit: "kg", estimated_price_per_unit: 120 },
    { name: "Tuna (canned)", category: "protein", default_unit: "pcs", estimated_price_per_unit: 15 },
    { name: "White fish (cod/tilapia)", category: "protein", default_unit: "kg", estimated_price_per_unit: 80 },
    { name: "Prawns", category: "protein", default_unit: "kg", estimated_price_per_unit: 150 },
    { name: "Merguez sausages", category: "protein", default_unit: "kg", estimated_price_per_unit: 70 },

    // === CARBS & GRAINS ===
    { name: "White rice", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { name: "Brown rice", category: "carbs", default_unit: "kg", estimated_price_per_unit: 18 },
    { name: "Basmati rice", category: "carbs", default_unit: "kg", estimated_price_per_unit: 22 },
    { name: "Potatoes", category: "carbs", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Sweet potatoes", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { name: "Quinoa", category: "carbs", default_unit: "kg", estimated_price_per_unit: 65 },
    { name: "Couscous", category: "carbs", default_unit: "kg", estimated_price_per_unit: 20 },
    { name: "Whole wheat pasta", category: "carbs", default_unit: "kg", estimated_price_per_unit: 25 },
    { name: "Regular pasta (spaghetti)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Pasta (penne)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Pasta (macaroni)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 14 },
    { name: "Vermicelli", category: "carbs", default_unit: "kg", estimated_price_per_unit: 16 },
    { name: "Oats", category: "carbs", default_unit: "kg", estimated_price_per_unit: 30 },
    { name: "Oat flakes", category: "carbs", default_unit: "kg", estimated_price_per_unit: 35 },
    { name: "Whole wheat bread", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 8 },
    { name: "White bread", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 5 },
    { name: "Khobz (Moroccan bread)", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 2 },
    { name: "Whole wheat tortillas", category: "carbs", default_unit: "pack", estimated_price_per_unit: 18 },
    { name: "Corn tortillas", category: "carbs", default_unit: "pack", estimated_price_per_unit: 12 },
    { name: "Rice noodles", category: "carbs", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Lentils (green)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 18 },
    { name: "Lentils (red)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 20 },
    { name: "Chickpeas (dried)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 20 },
    { name: "Chickpeas (canned)", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 10 },
    { name: "Black beans (canned)", category: "carbs", default_unit: "pcs", estimated_price_per_unit: 12 },
    { name: "White beans (dried)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 22 },
    { name: "Fava beans (dried)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Wheat flour", category: "carbs", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Whole wheat flour", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { name: "Semolina (fine)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Semolina (coarse)", category: "carbs", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Cornmeal", category: "carbs", default_unit: "kg", estimated_price_per_unit: 12 },
    { name: "Bulgur wheat", category: "carbs", default_unit: "kg", estimated_price_per_unit: 18 },
    { name: "Crackers", category: "carbs", default_unit: "pack", estimated_price_per_unit: 15 },

    // === VEGETABLES ===
    { name: "Tomatoes", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Cherry tomatoes", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Cucumber", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Bell peppers (red)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 25 },
    { name: "Bell peppers (green)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 18 },
    { name: "Bell peppers (yellow)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 25 },
    { name: "Onions (yellow)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 6 },
    { name: "Onions (red)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Garlic", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 2 },
    { name: "Shallots", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Carrots", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Broccoli", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 20 },
    { name: "Cauliflower", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 12 },
    { name: "Zucchini", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 12 },
    { name: "Eggplant", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Spinach", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 5 },
    { name: "Lettuce (romaine)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 6 },
    { name: "Lettuce (iceberg)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { name: "Mixed salad greens", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Green beans", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Mushrooms", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 18 },
    { name: "Celery", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 8 },
    { name: "Cabbage (white)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { name: "Cabbage (red)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 10 },
    { name: "Corn (fresh)", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 3 },
    { name: "Peas (frozen)", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 12 },
    { name: "Mixed vegetables (frozen)", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Leeks", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 10 },
    { name: "Turnips", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Beetroot", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Radishes", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 5 },
    { name: "Artichokes", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { name: "Asparagus", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 25 },
    { name: "Pumpkin", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 8 },
    { name: "Squash", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Green peas (fresh)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 18 },
    { name: "Broad beans (fresh)", category: "vegetables", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Fennel", category: "vegetables", default_unit: "pcs", estimated_price_per_unit: 8 },
    { name: "Spring onions", category: "vegetables", default_unit: "bunch", estimated_price_per_unit: 3 },
    { name: "Chili peppers", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 5 },
    { name: "Jalapeños", category: "vegetables", default_unit: "pack", estimated_price_per_unit: 8 },

    // === FRUITS ===
    { name: "Apples", category: "fruits", default_unit: "kg", estimated_price_per_unit: 20 },
    { name: "Bananas", category: "fruits", default_unit: "kg", estimated_price_per_unit: 12 },
    { name: "Oranges", category: "fruits", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Lemons", category: "fruits", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Limes", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 2 },
    { name: "Strawberries", category: "fruits", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Blueberries", category: "fruits", default_unit: "pack", estimated_price_per_unit: 35 },
    { name: "Grapes (green)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 30 },
    { name: "Grapes (red)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 32 },
    { name: "Watermelon", category: "fruits", default_unit: "kg", estimated_price_per_unit: 6 },
    { name: "Melon", category: "fruits", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Pineapple", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 20 },
    { name: "Avocado", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 12 },
    { name: "Dates (fresh)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 50 },
    { name: "Dates (dried)", category: "fruits", default_unit: "kg", estimated_price_per_unit: 40 },
    { name: "Dried apricots", category: "fruits", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Raisins", category: "fruits", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Dried figs", category: "fruits", default_unit: "pack", estimated_price_per_unit: 30 },
    { name: "Prunes", category: "fruits", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Mangoes", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 15 },
    { name: "Pears", category: "fruits", default_unit: "kg", estimated_price_per_unit: 25 },
    { name: "Peaches", category: "fruits", default_unit: "kg", estimated_price_per_unit: 22 },
    { name: "Plums", category: "fruits", default_unit: "kg", estimated_price_per_unit: 20 },
    { name: "Kiwis", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 5 },
    { name: "Pomegranate", category: "fruits", default_unit: "pcs", estimated_price_per_unit: 10 },

    // === DAIRY ===
    { name: "Greek yogurt", category: "dairy", default_unit: "kg", estimated_price_per_unit: 45 },
    { name: "Plain yogurt (Danone)", category: "dairy", default_unit: "pack", estimated_price_per_unit: 12 },
    { name: "Lben", category: "dairy", default_unit: "L", estimated_price_per_unit: 10 },
    { name: "Raib", category: "dairy", default_unit: "L", estimated_price_per_unit: 12 },
    { name: "Cottage cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Feta cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 30 },
    { name: "Mozzarella", category: "dairy", default_unit: "pack", estimated_price_per_unit: 35 },
    { name: "Cheddar cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 40 },
    { name: "Parmesan", category: "dairy", default_unit: "pack", estimated_price_per_unit: 50 },
    { name: "Jben (Moroccan cheese)", category: "dairy", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Cream cheese", category: "dairy", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Milk (whole)", category: "dairy", default_unit: "L", estimated_price_per_unit: 8 },
    { name: "Milk (skim)", category: "dairy", default_unit: "L", estimated_price_per_unit: 9 },
    { name: "Butter", category: "dairy", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Smen (Moroccan butter)", category: "dairy", default_unit: "jar", estimated_price_per_unit: 40 },
    { name: "Cream (cooking)", category: "dairy", default_unit: "pack", estimated_price_per_unit: 12 },
    { name: "Sour cream", category: "dairy", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Whipping cream", category: "dairy", default_unit: "pack", estimated_price_per_unit: 18 },

    // === NUTS & FATS ===
    { name: "Olive oil", category: "fats", default_unit: "L", estimated_price_per_unit: 80 },
    { name: "Argan oil", category: "fats", default_unit: "bottle", estimated_price_per_unit: 150 },
    { name: "Vegetable oil", category: "fats", default_unit: "L", estimated_price_per_unit: 18 },
    { name: "Coconut oil", category: "fats", default_unit: "jar", estimated_price_per_unit: 60 },
    { name: "Almonds", category: "fats", default_unit: "kg", estimated_price_per_unit: 120 },
    { name: "Walnuts", category: "fats", default_unit: "kg", estimated_price_per_unit: 140 },
    { name: "Peanuts (raw)", category: "fats", default_unit: "kg", estimated_price_per_unit: 40 },
    { name: "Peanuts (roasted)", category: "fats", default_unit: "kg", estimated_price_per_unit: 50 },
    { name: "Cashews", category: "fats", default_unit: "kg", estimated_price_per_unit: 160 },
    { name: "Pistachios", category: "fats", default_unit: "kg", estimated_price_per_unit: 180 },
    { name: "Hazelnuts", category: "fats", default_unit: "kg", estimated_price_per_unit: 130 },
    { name: "Pine nuts", category: "fats", default_unit: "pack", estimated_price_per_unit: 50 },
    { name: "Peanut butter", category: "fats", default_unit: "jar", estimated_price_per_unit: 45 },
    { name: "Almond butter", category: "fats", default_unit: "jar", estimated_price_per_unit: 80 },
    { name: "Tahini", category: "fats", default_unit: "jar", estimated_price_per_unit: 40 },
    { name: "Chia seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 50 },
    { name: "Flax seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 30 },
    { name: "Sunflower seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Pumpkin seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 35 },
    { name: "Sesame seeds", category: "fats", default_unit: "pack", estimated_price_per_unit: 15 },

    // === CONDIMENTS & SAUCES ===
    { name: "Soy sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 20 },
    { name: "Fish sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 25 },
    { name: "Sriracha", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 30 },
    { name: "Harissa", category: "condiments", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Teriyaki sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 35 },
    { name: "BBQ sauce", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 30 },
    { name: "Honey", category: "condiments", default_unit: "jar", estimated_price_per_unit: 50 },
    { name: "Maple syrup", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 80 },
    { name: "Mustard", category: "condiments", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Dijon mustard", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { name: "Mayonnaise", category: "condiments", default_unit: "jar", estimated_price_per_unit: 20 },
    { name: "Ketchup", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 15 },
    { name: "Tomato paste", category: "condiments", default_unit: "can", estimated_price_per_unit: 8 },
    { name: "Tomato sauce", category: "condiments", default_unit: "can", estimated_price_per_unit: 12 },
    { name: "Canned tomatoes (whole)", category: "condiments", default_unit: "can", estimated_price_per_unit: 10 },
    { name: "Canned tomatoes (diced)", category: "condiments", default_unit: "can", estimated_price_per_unit: 12 },
    { name: "Marinara sauce", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { name: "Salsa", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { name: "Hummus", category: "condiments", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Vinegar (balsamic)", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 35 },
    { name: "Vinegar (apple cider)", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 25 },
    { name: "Vinegar (white)", category: "condiments", default_unit: "bottle", estimated_price_per_unit: 10 },
    { name: "Coconut milk", category: "condiments", default_unit: "can", estimated_price_per_unit: 18 },
    { name: "Olives (green)", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },
    { name: "Olives (black)", category: "condiments", default_unit: "jar", estimated_price_per_unit: 28 },
    { name: "Pickles", category: "condiments", default_unit: "jar", estimated_price_per_unit: 20 },
    { name: "Capers", category: "condiments", default_unit: "jar", estimated_price_per_unit: 25 },

    // === HERBS & SPICES ===
    { name: "Fresh ginger", category: "herbs", default_unit: "pcs", estimated_price_per_unit: 5 },
    { name: "Fresh cilantro", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 3 },
    { name: "Fresh parsley", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 3 },
    { name: "Fresh basil", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { name: "Fresh mint", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 3 },
    { name: "Fresh rosemary", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { name: "Fresh thyme", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { name: "Fresh dill", category: "herbs", default_unit: "bunch", estimated_price_per_unit: 5 },
    { name: "Cumin (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { name: "Cumin (seeds)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Paprika", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { name: "Paprika (smoked)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 18 },
    { name: "Chili powder", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { name: "Cayenne pepper", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Turmeric", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Cinnamon (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { name: "Cinnamon sticks", category: "herbs", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Oregano (dried)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 10 },
    { name: "Mixed herbs", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Curry powder", category: "herbs", default_unit: "jar", estimated_price_per_unit: 18 },
    { name: "Garam masala", category: "herbs", default_unit: "jar", estimated_price_per_unit: 25 },
    { name: "Ras el hanout", category: "herbs", default_unit: "jar", estimated_price_per_unit: 20 },
    { name: "Saffron", category: "herbs", default_unit: "pack", estimated_price_per_unit: 60 },
    { name: "Black pepper (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Black pepper (whole)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 18 },
    { name: "Salt (table)", category: "herbs", default_unit: "pack", estimated_price_per_unit: 5 },
    { name: "Salt (sea)", category: "herbs", default_unit: "pack", estimated_price_per_unit: 8 },
    { name: "Bay leaves", category: "herbs", default_unit: "pack", estimated_price_per_unit: 10 },
    { name: "Coriander (ground)", category: "herbs", default_unit: "jar", estimated_price_per_unit: 12 },
    { name: "Cardamom", category: "herbs", default_unit: "pack", estimated_price_per_unit: 35 },
    { name: "Nutmeg", category: "herbs", default_unit: "pcs", estimated_price_per_unit: 5 },
    { name: "Cloves", category: "herbs", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Star anise", category: "herbs", default_unit: "pack", estimated_price_per_unit: 20 },

    // === BEVERAGES ===
    { name: "Green tea", category: "beverages", default_unit: "box", estimated_price_per_unit: 25 },
    { name: "Moroccan mint tea", category: "beverages", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Black tea", category: "beverages", default_unit: "box", estimated_price_per_unit: 20 },
    { name: "Coffee (ground)", category: "beverages", default_unit: "pack", estimated_price_per_unit: 50 },
    { name: "Coffee (instant)", category: "beverages", default_unit: "jar", estimated_price_per_unit: 40 },
    { name: "Coffee (beans)", category: "beverages", default_unit: "kg", estimated_price_per_unit: 80 },
    { name: "Sparkling water", category: "beverages", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Mineral water (5L)", category: "beverages", default_unit: "bottle", estimated_price_per_unit: 10 },
    { name: "Orange juice", category: "beverages", default_unit: "L", estimated_price_per_unit: 20 },
    { name: "Apple juice", category: "beverages", default_unit: "L", estimated_price_per_unit: 18 },

    // === SNACKS ===
    { name: "Protein bars", category: "snacks", default_unit: "box", estimated_price_per_unit: 80 },
    { name: "Dark chocolate (70%+)", category: "snacks", default_unit: "bar", estimated_price_per_unit: 25 },
    { name: "Rice cakes", category: "snacks", default_unit: "pack", estimated_price_per_unit: 18 },
    { name: "Trail mix", category: "snacks", default_unit: "pack", estimated_price_per_unit: 35 },
    { name: "Popcorn kernels", category: "snacks", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Granola", category: "snacks", default_unit: "pack", estimated_price_per_unit: 40 },
    { name: "Energy balls", category: "snacks", default_unit: "pack", estimated_price_per_unit: 30 },

    // === BAKING ===
    { name: "Baking powder", category: "baking", default_unit: "pack", estimated_price_per_unit: 8 },
    { name: "Baking soda", category: "baking", default_unit: "pack", estimated_price_per_unit: 5 },
    { name: "Yeast (dry)", category: "baking", default_unit: "pack", estimated_price_per_unit: 6 },
    { name: "Yeast (fresh)", category: "baking", default_unit: "pack", estimated_price_per_unit: 3 },
    { name: "Vanilla extract", category: "baking", default_unit: "bottle", estimated_price_per_unit: 25 },
    { name: "Cocoa powder", category: "baking", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Sugar (white)", category: "baking", default_unit: "kg", estimated_price_per_unit: 10 },
    { name: "Sugar (brown)", category: "baking", default_unit: "kg", estimated_price_per_unit: 15 },
    { name: "Powdered sugar", category: "baking", default_unit: "pack", estimated_price_per_unit: 12 },
    { name: "Chocolate chips", category: "baking", default_unit: "pack", estimated_price_per_unit: 30 },
    { name: "Almond flour", category: "baking", default_unit: "pack", estimated_price_per_unit: 45 },
    { name: "Coconut flour", category: "baking", default_unit: "pack", estimated_price_per_unit: 40 },

    // === CLEANING PRODUCTS ===
    { name: "Dish soap", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 15 },
    { name: "Dishwasher tablets", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 50 },
    { name: "Laundry detergent (liquid)", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 45 },
    { name: "Laundry detergent (powder)", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 40 },
    { name: "Fabric softener", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 30 },
    { name: "Bleach (Javel)", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 12 },
    { name: "All-purpose cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 20 },
    { name: "Glass cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 18 },
    { name: "Floor cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 25 },
    { name: "Toilet cleaner", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 18 },
    { name: "Sponges", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 10 },
    { name: "Steel wool", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 8 },
    { name: "Trash bags (large)", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Trash bags (small)", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Paper towels", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Toilet paper", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 30 },
    { name: "Tissues", category: "cleaning", default_unit: "box", estimated_price_per_unit: 15 },
    { name: "Hand soap", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 18 },
    { name: "Hand sanitizer", category: "cleaning", default_unit: "bottle", estimated_price_per_unit: 25 },
    { name: "Aluminum foil", category: "cleaning", default_unit: "roll", estimated_price_per_unit: 20 },
    { name: "Plastic wrap", category: "cleaning", default_unit: "roll", estimated_price_per_unit: 15 },
    { name: "Ziplock bags", category: "cleaning", default_unit: "pack", estimated_price_per_unit: 18 },
    { name: "Broom", category: "cleaning", default_unit: "pcs", estimated_price_per_unit: 35 },
    { name: "Mop", category: "cleaning", default_unit: "pcs", estimated_price_per_unit: 50 },
    { name: "Dustpan", category: "cleaning", default_unit: "pcs", estimated_price_per_unit: 20 },

    // === PERSONAL CARE ===
    { name: "Shampoo", category: "personal", default_unit: "bottle", estimated_price_per_unit: 35 },
    { name: "Conditioner", category: "personal", default_unit: "bottle", estimated_price_per_unit: 40 },
    { name: "Body wash", category: "personal", default_unit: "bottle", estimated_price_per_unit: 30 },
    { name: "Soap bars", category: "personal", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Toothpaste", category: "personal", default_unit: "tube", estimated_price_per_unit: 20 },
    { name: "Toothbrush", category: "personal", default_unit: "pcs", estimated_price_per_unit: 15 },
    { name: "Deodorant", category: "personal", default_unit: "pcs", estimated_price_per_unit: 30 },
    { name: "Razor blades", category: "personal", default_unit: "pack", estimated_price_per_unit: 40 },
    { name: "Shaving cream", category: "personal", default_unit: "can", estimated_price_per_unit: 35 },
    { name: "Cotton pads", category: "personal", default_unit: "pack", estimated_price_per_unit: 15 },
    { name: "Cotton swabs", category: "personal", default_unit: "pack", estimated_price_per_unit: 10 },
    { name: "Lotion", category: "personal", default_unit: "bottle", estimated_price_per_unit: 40 },
    { name: "Sunscreen", category: "personal", default_unit: "bottle", estimated_price_per_unit: 60 },

    // === BABY CARE ===
    { name: "Diapers", category: "baby", default_unit: "pack", estimated_price_per_unit: 80 },
    { name: "Baby wipes", category: "baby", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Baby formula", category: "baby", default_unit: "can", estimated_price_per_unit: 150 },
    { name: "Baby food", category: "baby", default_unit: "jar", estimated_price_per_unit: 15 },
    { name: "Baby shampoo", category: "baby", default_unit: "bottle", estimated_price_per_unit: 40 },

    // === PET CARE ===
    { name: "Cat food (dry)", category: "pets", default_unit: "kg", estimated_price_per_unit: 50 },
    { name: "Cat food (wet)", category: "pets", default_unit: "can", estimated_price_per_unit: 10 },
    { name: "Cat litter", category: "pets", default_unit: "kg", estimated_price_per_unit: 25 },
    { name: "Dog food (dry)", category: "pets", default_unit: "kg", estimated_price_per_unit: 40 },
    { name: "Dog food (wet)", category: "pets", default_unit: "can", estimated_price_per_unit: 15 },

    // === OTHER ===
    { name: "Bottled water (pack)", category: "other", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Ice cubes", category: "other", default_unit: "pack", estimated_price_per_unit: 10 },
    { name: "Candles", category: "other", default_unit: "pack", estimated_price_per_unit: 20 },
    { name: "Matches", category: "other", default_unit: "box", estimated_price_per_unit: 2 },
    { name: "Batteries (AA)", category: "other", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Batteries (AAA)", category: "other", default_unit: "pack", estimated_price_per_unit: 25 },
    { name: "Light bulbs", category: "other", default_unit: "pcs", estimated_price_per_unit: 15 },
];

// Get items by category
export function getGroceryItemsByCategory(): Record<string, GroceryItemTemplate[]> {
    return groceryItemTemplates.reduce((acc, item) => {
        if (!acc[item.category]) {
            acc[item.category] = [];
        }
        acc[item.category].push(item);
        return acc;
    }, {} as Record<string, GroceryItemTemplate[]>);
}

// Search items
export function searchGroceryItems(query: string): GroceryItemTemplate[] {
    const lower = query.toLowerCase();
    return groceryItemTemplates.filter(item =>
        item.name.toLowerCase().includes(lower) ||
        item.category.toLowerCase().includes(lower)
    );
}

// Category icons
export const categoryIcons: Record<string, string> = {
    protein: "🥩",
    carbs: "🍚",
    vegetables: "🥬",
    fruits: "🍎",
    dairy: "🧀",
    fats: "🥜",
    condiments: "🫙",
    herbs: "🌿",
    beverages: "🍵",
    snacks: "🍫",
    baking: "🧁",
    cleaning: "🧹",
    personal: "🧴",
    baby: "👶",
    pets: "🐾",
    other: "📦"
};

// Category display names
export const categoryNames: Record<string, string> = {
    protein: "Proteins & Meat",
    carbs: "Carbs & Grains",
    vegetables: "Vegetables",
    fruits: "Fruits",
    dairy: "Dairy",
    fats: "Nuts & Oils",
    condiments: "Condiments & Sauces",
    herbs: "Herbs & Spices",
    beverages: "Beverages",
    snacks: "Snacks",
    baking: "Baking",
    cleaning: "Cleaning Products",
    personal: "Personal Care",
    baby: "Baby Care",
    pets: "Pet Care",
    other: "Other"
};
