import { MealPlan } from './types';

// 50+ International Meal Plans
export const mealPlans: MealPlan[] = [
    // === MEDITERRANEAN ===
    {
        id: 1,
        name: "Greek Chicken Bowl",
        description: "Grilled chicken with cucumber, tomatoes, feta, and tzatziki",
        cuisine: "Mediterranean",
        prep_time: 25,
        calories: 450,
        protein: 42,
        carbs: 28,
        fat: 18,
        ingredients: ["300g chicken breast", "100g cucumber", "100g tomatoes", "30g feta", "50g tzatziki", "100g rice"],
        instructions: ["Grill seasoned chicken", "Dice vegetables", "Cook rice", "Assemble bowl with tzatziki"],
        image_emoji: "🥗",
        color_from: "#3b82f6",
        color_to: "#1d4ed8"
    },
    {
        id: 2,
        name: "Shakshuka",
        description: "Eggs poached in spiced tomato sauce with peppers",
        cuisine: "Mediterranean",
        prep_time: 20,
        calories: 380,
        protein: 24,
        carbs: 22,
        fat: 22,
        ingredients: ["4 eggs", "400g canned tomatoes", "1 bell pepper", "1 onion", "Cumin, paprika", "Fresh parsley"],
        instructions: ["Sauté onion and pepper", "Add tomatoes and spices", "Make wells and crack eggs", "Cover and cook until set"],
        image_emoji: "🍳",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 3,
        name: "Grilled Salmon with Lemon",
        description: "Fresh salmon with herbs, lemon, and roasted vegetables",
        cuisine: "Mediterranean",
        prep_time: 30,
        calories: 480,
        protein: 38,
        carbs: 20,
        fat: 28,
        ingredients: ["200g salmon fillet", "200g mixed vegetables", "1 lemon", "Olive oil", "Fresh dill"],
        instructions: ["Season salmon with herbs", "Roast vegetables", "Grill salmon 4 min each side", "Serve with lemon"],
        image_emoji: "🐟",
        color_from: "#f97316",
        color_to: "#ea580c"
    },

    // === ASIAN ===
    {
        id: 4,
        name: "Beef Teriyaki Bowl",
        description: "Tender beef strips with teriyaki glaze over rice",
        cuisine: "Asian",
        prep_time: 30,
        calories: 520,
        protein: 38,
        carbs: 45,
        fat: 20,
        ingredients: ["200g beef sirloin", "150g rice", "100g broccoli", "Teriyaki sauce", "Sesame seeds"],
        instructions: ["Slice beef thin", "Stir-fry on high heat", "Add teriyaki sauce", "Serve over rice with broccoli"],
        image_emoji: "🍜",
        color_from: "#f59e0b",
        color_to: "#d97706"
    },
    {
        id: 5,
        name: "Chicken Stir-Fry",
        description: "Quick chicken with vegetables in savory sauce",
        cuisine: "Asian",
        prep_time: 20,
        calories: 420,
        protein: 40,
        carbs: 30,
        fat: 16,
        ingredients: ["250g chicken breast", "200g mixed vegetables", "Soy sauce", "Ginger", "Garlic", "100g rice"],
        instructions: ["Cut chicken into pieces", "Stir-fry vegetables first", "Add chicken and sauce", "Serve with rice"],
        image_emoji: "🥢",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    {
        id: 6,
        name: "Shrimp Fried Rice",
        description: "Classic fried rice loaded with shrimp and vegetables",
        cuisine: "Asian",
        prep_time: 25,
        calories: 480,
        protein: 32,
        carbs: 52,
        fat: 16,
        ingredients: ["200g shrimp", "200g cooked rice", "2 eggs", "100g peas", "Soy sauce", "Green onions"],
        instructions: ["Scramble eggs, set aside", "Fry shrimp until pink", "Add cold rice and vegetables", "Mix in eggs and soy sauce"],
        image_emoji: "🍤",
        color_from: "#06b6d4",
        color_to: "#0891b2"
    },
    {
        id: 7,
        name: "Thai Basil Chicken",
        description: "Spicy ground chicken with Thai basil and chilies",
        cuisine: "Asian",
        prep_time: 15,
        calories: 440,
        protein: 38,
        carbs: 35,
        fat: 18,
        ingredients: ["250g ground chicken", "Thai basil leaves", "2 chilies", "Garlic", "Fish sauce", "150g rice"],
        instructions: ["Fry garlic and chilies", "Add chicken, break apart", "Season with fish sauce", "Toss with basil, serve over rice"],
        image_emoji: "🌶️",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },

    // === MEXICAN ===
    {
        id: 8,
        name: "Chicken Fajita Bowl",
        description: "Sizzling chicken with peppers and Mexican rice",
        cuisine: "Mexican",
        prep_time: 25,
        calories: 480,
        protein: 45,
        carbs: 35,
        fat: 18,
        ingredients: ["250g chicken breast", "2 bell peppers", "1 onion", "Fajita seasoning", "100g rice", "Salsa"],
        instructions: ["Slice chicken and vegetables", "Season and grill on high heat", "Cook Mexican rice", "Serve with salsa and lime"],
        image_emoji: "🌮",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 9,
        name: "Beef Burrito Bowl",
        description: "Seasoned beef with black beans, rice, and toppings",
        cuisine: "Mexican",
        prep_time: 30,
        calories: 550,
        protein: 42,
        carbs: 48,
        fat: 22,
        ingredients: ["200g ground beef", "100g black beans", "100g rice", "Cheese", "Sour cream", "Lettuce"],
        instructions: ["Brown beef with taco seasoning", "Warm black beans", "Cook cilantro lime rice", "Assemble bowl with toppings"],
        image_emoji: "🌯",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },
    {
        id: 10,
        name: "Fish Tacos",
        description: "Crispy fish with cabbage slaw and chipotle mayo",
        cuisine: "Mexican",
        prep_time: 25,
        calories: 420,
        protein: 32,
        carbs: 38,
        fat: 18,
        ingredients: ["200g white fish", "Corn tortillas", "Cabbage", "Lime", "Chipotle mayo", "Cilantro"],
        instructions: ["Season and pan-fry fish", "Shred cabbage, add lime", "Warm tortillas", "Assemble with slaw and sauce"],
        image_emoji: "🐠",
        color_from: "#14b8a6",
        color_to: "#0d9488"
    },

    // === ITALIAN ===
    {
        id: 11,
        name: "Chicken Pasta Marinara",
        description: "Grilled chicken over whole wheat pasta with tomato sauce",
        cuisine: "Italian",
        prep_time: 30,
        calories: 520,
        protein: 42,
        carbs: 55,
        fat: 14,
        ingredients: ["200g chicken breast", "150g whole wheat pasta", "200g marinara sauce", "Parmesan", "Fresh basil"],
        instructions: ["Grill seasoned chicken", "Cook pasta al dente", "Heat marinara sauce", "Combine and top with parmesan"],
        image_emoji: "🍝",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 12,
        name: "Grilled Chicken Caesar",
        description: "Classic Caesar salad with grilled chicken and croutons",
        cuisine: "Italian",
        prep_time: 20,
        calories: 420,
        protein: 40,
        carbs: 18,
        fat: 22,
        ingredients: ["200g chicken breast", "Romaine lettuce", "Caesar dressing", "Parmesan", "Croutons"],
        instructions: ["Grill chicken, slice", "Chop romaine lettuce", "Toss with dressing", "Top with chicken and parmesan"],
        image_emoji: "🥬",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    {
        id: 13,
        name: "Turkey Meatball Pasta",
        description: "Lean turkey meatballs in tomato sauce over pasta",
        cuisine: "Italian",
        prep_time: 35,
        calories: 490,
        protein: 38,
        carbs: 52,
        fat: 16,
        ingredients: ["200g ground turkey", "100g breadcrumbs", "1 egg", "Marinara sauce", "150g pasta", "Herbs"],
        instructions: ["Mix turkey with egg and breadcrumbs", "Form balls, bake 20 min", "Simmer in marinara", "Serve over pasta"],
        image_emoji: "🧆",
        color_from: "#a855f7",
        color_to: "#9333ea"
    },

    // === MIDDLE EASTERN ===
    {
        id: 14,
        name: "Chicken Shawarma Bowl",
        description: "Spiced chicken with tahini, pickles, and rice",
        cuisine: "Middle Eastern",
        prep_time: 35,
        calories: 490,
        protein: 44,
        carbs: 38,
        fat: 20,
        ingredients: ["250g chicken thigh", "Shawarma spices", "100g rice", "Tahini sauce", "Pickled vegetables", "Parsley"],
        instructions: ["Marinate chicken in spices", "Grill until charred", "Cook cumin rice", "Serve with tahini and pickles"],
        image_emoji: "🥙",
        color_from: "#a855f7",
        color_to: "#7c3aed"
    },
    {
        id: 15,
        name: "Kefta Kebabs",
        description: "Grilled spiced beef skewers with yogurt sauce",
        cuisine: "Middle Eastern",
        prep_time: 30,
        calories: 460,
        protein: 40,
        carbs: 25,
        fat: 24,
        ingredients: ["250g ground beef", "Onion", "Parsley", "Cumin, paprika", "Greek yogurt", "100g rice"],
        instructions: ["Mix beef with onion and spices", "Form onto skewers", "Grill 4 min each side", "Serve with yogurt sauce"],
        image_emoji: "🍢",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 16,
        name: "Lentil Soup",
        description: "Hearty red lentil soup with cumin and lemon",
        cuisine: "Middle Eastern",
        prep_time: 40,
        calories: 320,
        protein: 18,
        carbs: 48,
        fat: 8,
        ingredients: ["200g red lentils", "1 onion", "2 carrots", "Cumin, turmeric", "Lemon", "Olive oil"],
        instructions: ["Sauté onion and carrots", "Add lentils and water", "Simmer until soft", "Blend, serve with lemon"],
        image_emoji: "🍲",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },

    // === HIGH PROTEIN / SIMPLE ===
    {
        id: 17,
        name: "Steak & Eggs Power Plate",
        description: "Grilled steak with eggs and roasted vegetables",
        cuisine: "High Protein",
        prep_time: 20,
        calories: 580,
        protein: 52,
        carbs: 12,
        fat: 38,
        ingredients: ["200g beef steak", "3 eggs", "150g roasted vegetables", "Olive oil", "Herbs"],
        instructions: ["Season steak with salt and pepper", "Grill to preference", "Fry eggs sunny side up", "Serve with roasted vegetables"],
        image_emoji: "🥩",
        color_from: "#6366f1",
        color_to: "#4f46e5"
    },
    {
        id: 18,
        name: "Tuna Salad Wrap",
        description: "Light tuna salad in whole wheat wrap",
        cuisine: "High Protein",
        prep_time: 10,
        calories: 380,
        protein: 35,
        carbs: 30,
        fat: 14,
        ingredients: ["150g canned tuna", "Greek yogurt", "Celery", "Whole wheat wrap", "Lettuce", "Tomato"],
        instructions: ["Mix tuna with yogurt and celery", "Lay on wrap with vegetables", "Roll tightly", "Cut in half"],
        image_emoji: "🌯",
        color_from: "#0ea5e9",
        color_to: "#0284c7"
    },
    {
        id: 19,
        name: "Grilled Chicken & Sweet Potato",
        description: "Simple and clean meal prep staple",
        cuisine: "High Protein",
        prep_time: 35,
        calories: 450,
        protein: 42,
        carbs: 40,
        fat: 12,
        ingredients: ["250g chicken breast", "200g sweet potato", "Broccoli", "Olive oil", "Garlic powder"],
        instructions: ["Season chicken, grill 6 min each side", "Cube and roast sweet potato", "Steam broccoli", "Plate together"],
        image_emoji: "🍠",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 20,
        name: "Egg White Omelette",
        description: "Fluffy egg whites loaded with vegetables",
        cuisine: "High Protein",
        prep_time: 15,
        calories: 280,
        protein: 28,
        carbs: 12,
        fat: 12,
        ingredients: ["6 egg whites", "1 whole egg", "Spinach", "Mushrooms", "Cheese", "Tomatoes"],
        instructions: ["Whisk egg whites with whole egg", "Sauté vegetables", "Pour eggs, cook until set", "Fold and serve"],
        image_emoji: "🍳",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },

    // === SEAFOOD ===
    {
        id: 21,
        name: "Garlic Shrimp & Quinoa",
        description: "Succulent shrimp in garlic butter over quinoa",
        cuisine: "Seafood",
        prep_time: 25,
        calories: 420,
        protein: 36,
        carbs: 35,
        fat: 16,
        ingredients: ["250g shrimp", "150g quinoa", "Garlic", "Butter", "Lemon", "Parsley"],
        instructions: ["Cook quinoa", "Sauté garlic in butter", "Add shrimp, cook 3 min", "Finish with lemon and parsley"],
        image_emoji: "🦐",
        color_from: "#ec4899",
        color_to: "#db2777"
    },
    {
        id: 22,
        name: "Sardine Toast",
        description: "Omega-rich sardines on whole grain toast",
        cuisine: "Seafood",
        prep_time: 10,
        calories: 380,
        protein: 28,
        carbs: 32,
        fat: 18,
        ingredients: ["120g sardines", "2 slices whole grain bread", "Avocado", "Lemon", "Red onion", "Capers"],
        instructions: ["Toast bread", "Mash avocado on top", "Add sardines", "Top with onion, capers, lemon"],
        image_emoji: "🐟",
        color_from: "#0ea5e9",
        color_to: "#0284c7"
    },
    {
        id: 23,
        name: "Baked Cod with Vegetables",
        description: "Flaky white fish with roasted Mediterranean vegetables",
        cuisine: "Seafood",
        prep_time: 30,
        calories: 350,
        protein: 35,
        carbs: 22,
        fat: 14,
        ingredients: ["200g cod fillet", "Zucchini", "Bell peppers", "Cherry tomatoes", "Olive oil", "Herbs"],
        instructions: ["Season cod with herbs", "Arrange vegetables around fish", "Drizzle oil, bake 20 min at 200°C", "Serve hot"],
        image_emoji: "🐠",
        color_from: "#14b8a6",
        color_to: "#0d9488"
    },

    // === COMFORT FOOD (HEALTHIFIED) ===
    {
        id: 24,
        name: "Turkey Burger",
        description: "Lean turkey patty with all the fixings",
        cuisine: "American",
        prep_time: 20,
        calories: 420,
        protein: 38,
        carbs: 32,
        fat: 18,
        ingredients: ["200g ground turkey", "Whole wheat bun", "Lettuce", "Tomato", "Onion", "Mustard"],
        instructions: ["Form patty with seasonings", "Grill 5 min each side", "Toast bun", "Assemble with toppings"],
        image_emoji: "🍔",
        color_from: "#a855f7",
        color_to: "#9333ea"
    },
    {
        id: 25,
        name: "Chicken Quesadilla",
        description: "Crispy tortilla filled with chicken and cheese",
        cuisine: "Mexican",
        prep_time: 20,
        calories: 480,
        protein: 40,
        carbs: 38,
        fat: 20,
        ingredients: ["200g chicken", "2 tortillas", "Cheese", "Bell peppers", "Salsa", "Sour cream"],
        instructions: ["Shred cooked chicken", "Layer on tortilla with cheese", "Fold and pan-fry until crispy", "Serve with salsa"],
        image_emoji: "🧀",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },

    // More diverse meals...
    {
        id: 26,
        name: "Korean Beef Bowl",
        description: "Sweet and savory bulgogi-style beef over rice",
        cuisine: "Asian",
        prep_time: 25,
        calories: 510,
        protein: 38,
        carbs: 48,
        fat: 18,
        ingredients: ["200g beef", "Soy sauce", "Sesame oil", "Ginger", "Rice", "Green onions"],
        instructions: ["Slice beef thin", "Marinate in sauce", "Stir-fry quickly", "Serve over rice"],
        image_emoji: "🥘",
        color_from: "#dc2626",
        color_to: "#b91c1c"
    },
    {
        id: 27,
        name: "Chickpea Curry",
        description: "Creamy coconut chickpea curry with rice",
        cuisine: "Indian",
        prep_time: 30,
        calories: 420,
        protein: 16,
        carbs: 58,
        fat: 16,
        ingredients: ["200g chickpeas", "Coconut milk", "Curry paste", "Spinach", "Rice", "Cilantro"],
        instructions: ["Sauté onion and curry paste", "Add chickpeas and coconut milk", "Simmer 15 min, add spinach", "Serve over rice"],
        image_emoji: "🍛",
        color_from: "#f59e0b",
        color_to: "#d97706"
    },
    {
        id: 28,
        name: "Greek Lamb Kofta",
        description: "Spiced lamb skewers with tzatziki",
        cuisine: "Mediterranean",
        prep_time: 30,
        calories: 480,
        protein: 36,
        carbs: 28,
        fat: 26,
        ingredients: ["250g ground lamb", "Onion", "Mint", "Cumin", "Tzatziki", "Pita bread"],
        instructions: ["Mix lamb with spices and onion", "Form onto skewers", "Grill 4 min each side", "Serve with tzatziki and pita"],
        image_emoji: "🐑",
        color_from: "#8b5cf6",
        color_to: "#7c3aed"
    },
    {
        id: 29,
        name: "Vietnamese Pho",
        description: "Aromatic beef noodle soup",
        cuisine: "Asian",
        prep_time: 45,
        calories: 420,
        protein: 32,
        carbs: 48,
        fat: 12,
        ingredients: ["200g beef", "Rice noodles", "Beef broth", "Star anise", "Bean sprouts", "Herbs"],
        instructions: ["Simmer broth with spices", "Cook noodles separately", "Slice beef thin", "Assemble and pour hot broth over"],
        image_emoji: "🍜",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    {
        id: 30,
        name: "Moroccan Chicken Tagine",
        description: "Slow-cooked chicken with olives and preserved lemon",
        cuisine: "Moroccan",
        prep_time: 50,
        calories: 460,
        protein: 40,
        carbs: 32,
        fat: 20,
        ingredients: ["300g chicken", "Olives", "Preserved lemon", "Onions", "Saffron", "Couscous"],
        instructions: ["Brown chicken pieces", "Add onions and spices", "Slow cook with olives and lemon", "Serve over couscous"],
        image_emoji: "🫕",
        color_from: "#f97316",
        color_to: "#ea580c"
    },

    // Add more variety...
    {
        id: 31,
        name: "Protein Pancakes",
        description: "Fluffy pancakes with banana and protein",
        cuisine: "Breakfast",
        prep_time: 15,
        calories: 380,
        protein: 28,
        carbs: 42,
        fat: 12,
        ingredients: ["2 eggs", "1 banana", "Oats", "Greek yogurt", "Honey", "Berries"],
        instructions: ["Blend eggs, banana, and oats", "Cook like regular pancakes", "Top with yogurt and berries"],
        image_emoji: "🥞",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },
    {
        id: 32,
        name: "Avocado Toast with Eggs",
        description: "Trendy and nutritious breakfast",
        cuisine: "Breakfast",
        prep_time: 10,
        calories: 420,
        protein: 18,
        carbs: 32,
        fat: 28,
        ingredients: ["2 eggs", "1 avocado", "Whole grain bread", "Chili flakes", "Lime", "Salt"],
        instructions: ["Toast bread", "Mash avocado with lime", "Spread on toast", "Top with poached eggs"],
        image_emoji: "🥑",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 33,
        name: "Overnight Oats",
        description: "No-cook prep-ahead breakfast",
        cuisine: "Breakfast",
        prep_time: 5,
        calories: 350,
        protein: 15,
        carbs: 52,
        fat: 10,
        ingredients: ["80g oats", "200ml milk", "Greek yogurt", "Chia seeds", "Honey", "Fruit"],
        instructions: ["Mix all ingredients", "Refrigerate overnight", "Top with fresh fruit in morning"],
        image_emoji: "🥣",
        color_from: "#a855f7",
        color_to: "#9333ea"
    },

    // Continue with more meals for variety...
    {
        id: 34,
        name: "BBQ Chicken Thighs",
        description: "Juicy grilled chicken with BBQ glaze",
        cuisine: "American",
        prep_time: 35,
        calories: 480,
        protein: 42,
        carbs: 25,
        fat: 24,
        ingredients: ["300g chicken thighs", "BBQ sauce", "Coleslaw", "Corn on cob", "Pickles"],
        instructions: ["Grill chicken, basting with BBQ sauce", "Char corn on grill", "Serve with coleslaw"],
        image_emoji: "🍗",
        color_from: "#dc2626",
        color_to: "#b91c1c"
    },
    {
        id: 35,
        name: "Stuffed Bell Peppers",
        description: "Peppers filled with beef, rice, and cheese",
        cuisine: "American",
        prep_time: 45,
        calories: 420,
        protein: 32,
        carbs: 35,
        fat: 18,
        ingredients: ["4 bell peppers", "200g ground beef", "100g rice", "Tomato sauce", "Cheese", "Onion"],
        instructions: ["Hollow out peppers", "Mix cooked beef with rice", "Stuff peppers, top with sauce and cheese", "Bake 25 min"],
        image_emoji: "🫑",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 36,
        name: "Egg Fried Rice",
        description: "Quick and satisfying rice dish",
        cuisine: "Asian",
        prep_time: 15,
        calories: 420,
        protein: 16,
        carbs: 58,
        fat: 14,
        ingredients: ["200g cooked rice", "3 eggs", "Peas", "Carrots", "Soy sauce", "Green onions"],
        instructions: ["Scramble eggs, set aside", "Stir-fry vegetables and rice", "Add eggs and soy sauce", "Garnish with green onions"],
        image_emoji: "🍚",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },
    {
        id: 37,
        name: "Lamb Chops with Mint",
        description: "Pan-seared lamb with fresh mint sauce",
        cuisine: "Mediterranean",
        prep_time: 25,
        calories: 520,
        protein: 40,
        carbs: 15,
        fat: 35,
        ingredients: ["4 lamb chops", "Fresh mint", "Yogurt", "Garlic", "Roasted potatoes", "Green beans"],
        instructions: ["Season and sear lamb chops", "Make mint yogurt sauce", "Roast potatoes", "Serve together"],
        image_emoji: "🥩",
        color_from: "#8b5cf6",
        color_to: "#7c3aed"
    },
    {
        id: 38,
        name: "Spicy Tuna Poke Bowl",
        description: "Fresh raw tuna with rice and toppings",
        cuisine: "Asian",
        prep_time: 20,
        calories: 450,
        protein: 35,
        carbs: 48,
        fat: 14,
        ingredients: ["200g sushi-grade tuna", "Sushi rice", "Avocado", "Cucumber", "Sriracha mayo", "Nori"],
        instructions: ["Cube tuna, marinate in soy and sesame", "Cook sushi rice", "Arrange toppings in bowl", "Drizzle with spicy mayo"],
        image_emoji: "🍣",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 39,
        name: "Cottage Cheese Salad",
        description: "High protein refreshing salad",
        cuisine: "High Protein",
        prep_time: 10,
        calories: 280,
        protein: 28,
        carbs: 18,
        fat: 12,
        ingredients: ["200g cottage cheese", "Cherry tomatoes", "Cucumber", "Olive oil", "Fresh herbs", "Black pepper"],
        instructions: ["Chop vegetables", "Place cottage cheese in bowl", "Top with vegetables and drizzle oil"],
        image_emoji: "🧀",
        color_from: "#f8fafc",
        color_to: "#e2e8f0"
    },
    {
        id: 40,
        name: "Honey Garlic Chicken",
        description: "Sticky sweet chicken with vegetables",
        cuisine: "Asian",
        prep_time: 30,
        calories: 460,
        protein: 40,
        carbs: 38,
        fat: 16,
        ingredients: ["300g chicken thighs", "Honey", "Soy sauce", "Garlic", "Rice", "Steamed broccoli"],
        instructions: ["Make honey garlic sauce", "Cook chicken, add sauce", "Simmer until sticky", "Serve with rice and broccoli"],
        image_emoji: "🍯",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },

    // Even more variety
    {
        id: 41,
        name: "Beef Stroganoff",
        description: "Creamy beef strips over egg noodles",
        cuisine: "Russian",
        prep_time: 35,
        calories: 520,
        protein: 38,
        carbs: 42,
        fat: 24,
        ingredients: ["200g beef sirloin", "Mushro oms", "Sour cream", "Onion", "Egg noodles", "Beef broth"],
        instructions: ["Sear beef strips", "Sauté mushrooms and onion", "Add broth and sour cream", "Serve over noodles"],
        image_emoji: "🥘",
        color_from: "#78716c",
        color_to: "#57534e"
    },
    {
        id: 42,
        name: "Caprese Chicken",
        description: "Chicken topped with tomato, mozzarella, and basil",
        cuisine: "Italian",
        prep_time: 25,
        calories: 420,
        protein: 45,
        carbs: 8,
        fat: 24,
        ingredients: ["200g chicken breast", "Fresh mozzarella", "Tomatoes", "Fresh basil", "Balsamic glaze", "Olive oil"],
        instructions: ["Grill chicken", "Top with tomato and mozzarella", "Broil until cheese melts", "Drizzle balsamic and basil"],
        image_emoji: "🍅",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 43,
        name: "Harira Soup",
        description: "Traditional Moroccan lentil and chickpea soup",
        cuisine: "Moroccan",
        prep_time: 45,
        calories: 350,
        protein: 18,
        carbs: 52,
        fat: 8,
        ingredients: ["Lentils", "Chickpeas", "Tomatoes", "Celery", "Onion", "Moroccan spices", "Cilantro"],
        instructions: ["Sauté vegetables", "Add lentils, chickpeas, tomatoes", "Simmer until tender", "Finish with cilantro and lemon"],
        image_emoji: "🍲",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 44,
        name: "Spinach and Feta Stuffed Chicken",
        description: "Chicken breast stuffed with Mediterranean flavors",
        cuisine: "Mediterranean",
        prep_time: 35,
        calories: 420,
        protein: 48,
        carbs: 6,
        fat: 24,
        ingredients: ["200g chicken breast", "Spinach", "Feta cheese", "Garlic", "Sun-dried tomatoes", "Olive oil"],
        instructions: ["Cut pocket in chicken", "Mix spinach, feta, garlic", "Stuff chicken", "Bake 25 min at 200°C"],
        image_emoji: "🥗",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 45,
        name: "Black Bean Tacos",
        description: "Vegetarian tacos with all the fixings",
        cuisine: "Mexican",
        prep_time: 20,
        calories: 380,
        protein: 16,
        carbs: 52,
        fat: 14,
        ingredients: ["200g black beans", "Corn tortillas", "Avocado", "Salsa", "Lime", "Cilantro"],
        instructions: ["Warm and season beans", "Warm tortillas", "Fill with beans and toppings", "Squeeze lime over"],
        image_emoji: "🌮",
        color_from: "#1e293b",
        color_to: "#0f172a"
    },
    {
        id: 46,
        name: "Lemon Herb Roast Chicken",
        description: "Whole roasted chicken with herbs",
        cuisine: "French",
        prep_time: 75,
        calories: 380,
        protein: 42,
        carbs: 4,
        fat: 22,
        ingredients: ["Whole chicken", "Lemon", "Garlic", "Rosemary", "Thyme", "Butter"],
        instructions: ["Stuff with lemon and garlic", "Rub with butter and herbs", "Roast 1 hour at 200°C", "Rest before carving"],
        image_emoji: "🍋",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },
    {
        id: 47,
        name: "Prawn Linguine",
        description: "Garlic prawns tossed with pasta",
        cuisine: "Italian",
        prep_time: 25,
        calories: 480,
        protein: 32,
        carbs: 52,
        fat: 16,
        ingredients: ["200g prawns", "150g linguine", "Garlic", "White wine", "Chili flakes", "Parsley"],
        instructions: ["Cook pasta", "Sauté garlic and prawns", "Deglaze with wine", "Toss with pasta and herbs"],
        image_emoji: "🦐",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 48,
        name: "Chicken Tikka Masala",
        description: "Creamy tomato curry with tender chicken",
        cuisine: "Indian",
        prep_time: 40,
        calories: 480,
        protein: 38,
        carbs: 32,
        fat: 24,
        ingredients: ["300g chicken", "Yogurt", "Tomato sauce", "Cream", "Garam masala", "Rice"],
        instructions: ["Marinate chicken in spiced yogurt", "Grill until charred", "Simmer in tomato cream sauce", "Serve with rice"],
        image_emoji: "🍛",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 49,
        name: "Beef Bibimbap",
        description: "Korean rice bowl with vegetables and egg",
        cuisine: "Asian",
        prep_time: 35,
        calories: 520,
        protein: 32,
        carbs: 58,
        fat: 18,
        ingredients: ["150g beef", "Rice", "Spinach", "Carrots", "Zucchini", "Egg", "Gochujang"],
        instructions: ["Cook rice", "Prepare and season each vegetable", "Cook beef with soy sauce", "Arrange in bowl, top with fried egg"],
        image_emoji: "🍳",
        color_from: "#dc2626",
        color_to: "#b91c1c"
    },
    {
        id: 50,
        name: "Grilled Vegetable Plate",
        description: "Colorful grilled vegetables with hummus",
        cuisine: "Mediterranean",
        prep_time: 25,
        calories: 320,
        protein: 12,
        carbs: 38,
        fat: 16,
        ingredients: ["Zucchini", "Eggplant", "Bell peppers", "Onion", "Hummus", "Olive oil"],
        instructions: ["Slice all vegetables", "Brush with oil, season", "Grill until charred", "Serve with hummus"],
        image_emoji: "🥕",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    // === BATCH 2: MORE MEDITERRANEAN ===
    { id: 51, name: "Falafel Bowl", description: "Crispy chickpea falafel with tahini", cuisine: "Mediterranean", prep_time: 35, calories: 420, protein: 18, carbs: 52, fat: 18, ingredients: ["Chickpeas", "Herbs", "Tahini", "Pita", "Tomatoes", "Cucumber"], instructions: ["Make falafel mixture", "Fry until golden", "Serve with vegetables"], image_emoji: "🧆", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 52, name: "Grilled Halloumi Salad", description: "Salty halloumi with fresh greens", cuisine: "Mediterranean", prep_time: 15, calories: 380, protein: 22, carbs: 18, fat: 26, ingredients: ["Halloumi", "Mixed greens", "Tomatoes", "Olives", "Lemon"], instructions: ["Grill halloumi", "Toss salad", "Serve warm"], image_emoji: "🧀", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 53, name: "Moussaka", description: "Layered eggplant and meat casserole", cuisine: "Mediterranean", prep_time: 60, calories: 480, protein: 28, carbs: 35, fat: 26, ingredients: ["Eggplant", "Ground lamb", "Tomato sauce", "Béchamel"], instructions: ["Layer ingredients", "Bake until golden"], image_emoji: "🍆", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 54, name: "Tabbouleh", description: "Fresh parsley and bulgur salad", cuisine: "Mediterranean", prep_time: 20, calories: 180, protein: 6, carbs: 32, fat: 6, ingredients: ["Bulgur", "Parsley", "Tomatoes", "Mint", "Lemon"], instructions: ["Soak bulgur", "Chop herbs", "Mix all"], image_emoji: "🥗", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 55, name: "Hummus with Pita", description: "Creamy chickpea dip", cuisine: "Mediterranean", prep_time: 10, calories: 320, protein: 12, carbs: 42, fat: 14, ingredients: ["Chickpeas", "Tahini", "Garlic", "Lemon", "Pita"], instructions: ["Blend ingredients", "Serve with warm pita"], image_emoji: "🫓", color_from: "#f59e0b", color_to: "#d97706" },
    // === MORE ASIAN ===
    { id: 56, name: "Pad Thai", description: "Thai stir-fried rice noodles", cuisine: "Asian", prep_time: 25, calories: 480, protein: 24, carbs: 58, fat: 18, ingredients: ["Rice noodles", "Shrimp", "Eggs", "Bean sprouts", "Peanuts"], instructions: ["Soak noodles", "Stir-fry all", "Add sauce"], image_emoji: "🍜", color_from: "#f97316", color_to: "#ea580c" },
    { id: 57, name: "Sushi Bowl", description: "Deconstructed sushi in a bowl", cuisine: "Asian", prep_time: 30, calories: 420, protein: 22, carbs: 55, fat: 12, ingredients: ["Sushi rice", "Salmon", "Avocado", "Cucumber", "Nori"], instructions: ["Cook rice", "Slice fish", "Arrange bowl"], image_emoji: "🍣", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 58, name: "Miso Soup with Tofu", description: "Traditional Japanese soup", cuisine: "Asian", prep_time: 15, calories: 120, protein: 10, carbs: 12, fat: 4, ingredients: ["Miso paste", "Tofu", "Seaweed", "Green onion"], instructions: ["Heat dashi", "Add miso", "Add tofu"], image_emoji: "🍲", color_from: "#a855f7", color_to: "#9333ea" },
    { id: 59, name: "Orange Chicken", description: "Crispy chicken in citrus sauce", cuisine: "Asian", prep_time: 35, calories: 520, protein: 32, carbs: 48, fat: 22, ingredients: ["Chicken", "Orange juice", "Soy sauce", "Ginger", "Rice"], instructions: ["Fry chicken", "Make sauce", "Toss together"], image_emoji: "🍊", color_from: "#f97316", color_to: "#ea580c" },
    { id: 60, name: "Vegetable Dumplings", description: "Steamed dumplings with veggies", cuisine: "Asian", prep_time: 40, calories: 280, protein: 10, carbs: 42, fat: 8, ingredients: ["Dumpling wrappers", "Cabbage", "Carrots", "Mushrooms"], instructions: ["Make filling", "Wrap", "Steam"], image_emoji: "🥟", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 61, name: "Tofu Stir-Fry", description: "Crispy tofu with vegetables", cuisine: "Asian", prep_time: 25, calories: 320, protein: 18, carbs: 28, fat: 16, ingredients: ["Tofu", "Broccoli", "Bell peppers", "Soy sauce"], instructions: ["Press tofu", "Fry until crispy", "Add vegetables"], image_emoji: "🥦", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 62, name: "Ramen Bowl", description: "Rich broth with noodles", cuisine: "Asian", prep_time: 45, calories: 520, protein: 28, carbs: 55, fat: 22, ingredients: ["Ramen noodles", "Pork broth", "Egg", "Chashu", "Nori"], instructions: ["Make broth", "Cook noodles", "Assemble"], image_emoji: "🍜", color_from: "#dc2626", color_to: "#b91c1c" },
    // === INDIAN ===
    { id: 63, name: "Palak Paneer", description: "Spinach curry with cheese", cuisine: "Indian", prep_time: 30, calories: 380, protein: 18, carbs: 22, fat: 26, ingredients: ["Spinach", "Paneer", "Onion", "Cream", "Spices"], instructions: ["Blend spinach", "Fry paneer", "Combine"], image_emoji: "🥬", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 64, name: "Dal Tadka", description: "Spiced lentil curry", cuisine: "Indian", prep_time: 35, calories: 320, protein: 18, carbs: 48, fat: 8, ingredients: ["Yellow lentils", "Tomatoes", "Garlic", "Cumin", "Ghee"], instructions: ["Cook lentils", "Make tadka", "Combine"], image_emoji: "🍛", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 65, name: "Butter Chicken", description: "Creamy tomato chicken curry", cuisine: "Indian", prep_time: 40, calories: 520, protein: 38, carbs: 28, fat: 30, ingredients: ["Chicken", "Tomato sauce", "Cream", "Butter", "Garam masala"], instructions: ["Grill chicken", "Make sauce", "Simmer"], image_emoji: "🍗", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 66, name: "Chana Masala", description: "Spiced chickpea curry", cuisine: "Indian", prep_time: 30, calories: 340, protein: 14, carbs: 52, fat: 10, ingredients: ["Chickpeas", "Tomatoes", "Onion", "Spices", "Cilantro"], instructions: ["Sauté aromatics", "Add chickpeas", "Simmer"], image_emoji: "🫘", color_from: "#f97316", color_to: "#ea580c" },
    { id: 67, name: "Tandoori Cauliflower", description: "Roasted spiced cauliflower", cuisine: "Indian", prep_time: 35, calories: 180, protein: 8, carbs: 22, fat: 8, ingredients: ["Cauliflower", "Yogurt", "Tandoori spices", "Lemon"], instructions: ["Marinate", "Roast until charred"], image_emoji: "🥬", color_from: "#f97316", color_to: "#ea580c" },
    { id: 68, name: "Aloo Gobi", description: "Potato and cauliflower curry", cuisine: "Indian", prep_time: 30, calories: 280, protein: 8, carbs: 42, fat: 10, ingredients: ["Potatoes", "Cauliflower", "Turmeric", "Cumin", "Tomatoes"], instructions: ["Fry spices", "Add vegetables", "Cook until tender"], image_emoji: "🥔", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 69, name: "Lamb Biryani", description: "Fragrant rice with lamb", cuisine: "Indian", prep_time: 60, calories: 580, protein: 32, carbs: 62, fat: 24, ingredients: ["Basmati rice", "Lamb", "Saffron", "Onions", "Spices"], instructions: ["Cook lamb", "Layer with rice", "Steam"], image_emoji: "🍚", color_from: "#a855f7", color_to: "#9333ea" },
    { id: 70, name: "Samosas", description: "Crispy potato pastries", cuisine: "Indian", prep_time: 45, calories: 320, protein: 8, carbs: 42, fat: 14, ingredients: ["Potatoes", "Peas", "Pastry", "Cumin", "Coriander"], instructions: ["Make filling", "Wrap", "Fry"], image_emoji: "🥟", color_from: "#f59e0b", color_to: "#d97706" },
    // === MORE MEXICAN ===
    { id: 71, name: "Carnitas Tacos", description: "Slow-cooked pulled pork tacos", cuisine: "Mexican", prep_time: 180, calories: 480, protein: 32, carbs: 38, fat: 24, ingredients: ["Pork shoulder", "Orange", "Garlic", "Tortillas", "Onion"], instructions: ["Slow cook pork", "Shred", "Serve in tortillas"], image_emoji: "🌮", color_from: "#f97316", color_to: "#ea580c" },
    { id: 72, name: "Chicken Enchiladas", description: "Rolled tortillas in red sauce", cuisine: "Mexican", prep_time: 45, calories: 520, protein: 35, carbs: 42, fat: 24, ingredients: ["Chicken", "Tortillas", "Enchilada sauce", "Cheese", "Onion"], instructions: ["Roll filling", "Cover with sauce", "Bake"], image_emoji: "🌯", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 73, name: "Ceviche", description: "Fresh lime-cured fish", cuisine: "Mexican", prep_time: 30, calories: 220, protein: 28, carbs: 12, fat: 8, ingredients: ["White fish", "Lime", "Tomatoes", "Onion", "Cilantro"], instructions: ["Dice fish", "Cure in lime", "Add vegetables"], image_emoji: "🐟", color_from: "#06b6d4", color_to: "#0891b2" },
    { id: 74, name: "Pozole", description: "Traditional hominy soup", cuisine: "Mexican", prep_time: 90, calories: 420, protein: 28, carbs: 45, fat: 16, ingredients: ["Pork", "Hominy", "Dried chilies", "Cabbage", "Radish"], instructions: ["Simmer pork", "Add hominy", "Top with garnishes"], image_emoji: "🍲", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 75, name: "Guacamole", description: "Fresh avocado dip", cuisine: "Mexican", prep_time: 10, calories: 180, protein: 3, carbs: 12, fat: 16, ingredients: ["Avocados", "Lime", "Onion", "Tomato", "Cilantro"], instructions: ["Mash avocado", "Mix ingredients"], image_emoji: "🥑", color_from: "#22c55e", color_to: "#16a34a" },
    // === HIGH PROTEIN ===
    { id: 76, name: "Greek Yogurt Parfait", description: "Protein-rich breakfast", cuisine: "Breakfast", prep_time: 5, calories: 320, protein: 25, carbs: 35, fat: 10, ingredients: ["Greek yogurt", "Granola", "Berries", "Honey"], instructions: ["Layer ingredients"], image_emoji: "🍓", color_from: "#ec4899", color_to: "#db2777" },
    { id: 77, name: "Chicken Breast with Quinoa", description: "Clean eating staple", cuisine: "High Protein", prep_time: 30, calories: 450, protein: 45, carbs: 35, fat: 14, ingredients: ["Chicken breast", "Quinoa", "Broccoli", "Lemon"], instructions: ["Grill chicken", "Cook quinoa", "Serve together"], image_emoji: "🍗", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 78, name: "Turkey Lettuce Wraps", description: "Low-carb protein meal", cuisine: "High Protein", prep_time: 20, calories: 280, protein: 32, carbs: 12, fat: 12, ingredients: ["Ground turkey", "Lettuce", "Water chestnuts", "Soy sauce"], instructions: ["Cook turkey", "Wrap in lettuce"], image_emoji: "🥬", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 79, name: "Beef Stir-Fry", description: "High protein with vegetables", cuisine: "High Protein", prep_time: 20, calories: 420, protein: 38, carbs: 22, fat: 22, ingredients: ["Beef sirloin", "Broccoli", "Bell peppers", "Soy sauce"], instructions: ["Slice beef", "Stir-fry", "Serve"], image_emoji: "🥩", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 80, name: "Cod with Asparagus", description: "Light and lean fish dinner", cuisine: "Seafood", prep_time: 25, calories: 320, protein: 38, carbs: 12, fat: 14, ingredients: ["Cod fillet", "Asparagus", "Lemon", "Garlic"], instructions: ["Bake cod", "Roast asparagus"], image_emoji: "🐟", color_from: "#14b8a6", color_to: "#0d9488" },
    // === VEGETARIAN ===
    { id: 81, name: "Buddha Bowl", description: "Colorful grain and veggie bowl", cuisine: "Vegetarian", prep_time: 30, calories: 420, protein: 15, carbs: 58, fat: 16, ingredients: ["Quinoa", "Chickpeas", "Sweet potato", "Kale", "Tahini"], instructions: ["Cook grains", "Roast vegetables", "Assemble"], image_emoji: "🥗", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 82, name: "Mushroom Risotto", description: "Creamy Italian rice dish", cuisine: "Vegetarian", prep_time: 40, calories: 480, protein: 12, carbs: 62, fat: 20, ingredients: ["Arborio rice", "Mushrooms", "Parmesan", "White wine"], instructions: ["Toast rice", "Add broth slowly", "Stir in cheese"], image_emoji: "🍄", color_from: "#78716c", color_to: "#57534e" },
    { id: 83, name: "Veggie Curry", description: "Mixed vegetable coconut curry", cuisine: "Vegetarian", prep_time: 35, calories: 380, protein: 12, carbs: 48, fat: 18, ingredients: ["Mixed vegetables", "Coconut milk", "Curry paste", "Rice"], instructions: ["Sauté vegetables", "Add coconut milk", "Simmer"], image_emoji: "🍛", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 84, name: "Caprese Salad", description: "Fresh tomato and mozzarella", cuisine: "Vegetarian", prep_time: 10, calories: 280, protein: 14, carbs: 8, fat: 22, ingredients: ["Tomatoes", "Mozzarella", "Basil", "Balsamic"], instructions: ["Slice and arrange", "Drizzle"], image_emoji: "🍅", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 85, name: "Eggplant Parmesan", description: "Breaded eggplant with cheese", cuisine: "Vegetarian", prep_time: 45, calories: 420, protein: 18, carbs: 38, fat: 24, ingredients: ["Eggplant", "Breadcrumbs", "Marinara", "Mozzarella"], instructions: ["Bread eggplant", "Fry", "Bake with cheese"], image_emoji: "🍆", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 86, name: "Spinach Artichoke Pasta", description: "Creamy vegetarian pasta", cuisine: "Vegetarian", prep_time: 25, calories: 480, protein: 16, carbs: 55, fat: 22, ingredients: ["Pasta", "Spinach", "Artichokes", "Cream", "Parmesan"], instructions: ["Cook pasta", "Make sauce", "Combine"], image_emoji: "🍝", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 87, name: "Stuffed Portobello", description: "Mushrooms with quinoa filling", cuisine: "Vegetarian", prep_time: 35, calories: 320, protein: 14, carbs: 35, fat: 16, ingredients: ["Portobello mushrooms", "Quinoa", "Spinach", "Feta"], instructions: ["Prep mushrooms", "Make filling", "Bake"], image_emoji: "🍄", color_from: "#78716c", color_to: "#57534e" },
    // === SALADS ===
    { id: 88, name: "Cobb Salad", description: "Classic American salad", cuisine: "Salads", prep_time: 20, calories: 420, protein: 32, carbs: 12, fat: 30, ingredients: ["Chicken", "Bacon", "Egg", "Avocado", "Blue cheese"], instructions: ["Chop ingredients", "Arrange in rows"], image_emoji: "🥗", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 89, name: "Asian Chicken Salad", description: "Crispy noodles and sesame", cuisine: "Salads", prep_time: 25, calories: 380, protein: 28, carbs: 28, fat: 18, ingredients: ["Chicken", "Cabbage", "Mandarin oranges", "Sesame dressing"], instructions: ["Grill chicken", "Toss salad"], image_emoji: "🥗", color_from: "#f97316", color_to: "#ea580c" },
    { id: 90, name: "Niçoise Salad", description: "French tuna salad", cuisine: "Salads", prep_time: 25, calories: 420, protein: 30, carbs: 22, fat: 26, ingredients: ["Tuna", "Green beans", "Potatoes", "Olives", "Eggs"], instructions: ["Prepare components", "Arrange beautifully"], image_emoji: "🐟", color_from: "#3b82f6", color_to: "#1d4ed8" },
    { id: 91, name: "Kale Caesar", description: "Hearty kale with caesar dressing", cuisine: "Salads", prep_time: 15, calories: 320, protein: 12, carbs: 22, fat: 22, ingredients: ["Kale", "Parmesan", "Croutons", "Caesar dressing"], instructions: ["Massage kale", "Toss with dressing"], image_emoji: "🥬", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 92, name: "Quinoa Tabbouleh", description: "Protein-rich grain salad", cuisine: "Salads", prep_time: 25, calories: 280, protein: 10, carbs: 42, fat: 10, ingredients: ["Quinoa", "Parsley", "Tomatoes", "Cucumber", "Lemon"], instructions: ["Cook quinoa", "Chop herbs", "Mix all"], image_emoji: "🥗", color_from: "#22c55e", color_to: "#16a34a" },
    // === SEAFOOD ===
    { id: 93, name: "Grilled Mahi Mahi", description: "Tropical fish with mango salsa", cuisine: "Seafood", prep_time: 25, calories: 320, protein: 35, carbs: 18, fat: 12, ingredients: ["Mahi mahi", "Mango", "Red onion", "Cilantro", "Lime"], instructions: ["Grill fish", "Make salsa", "Top and serve"], image_emoji: "🐟", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 94, name: "Coconut Shrimp", description: "Crispy coconut-crusted shrimp", cuisine: "Seafood", prep_time: 30, calories: 380, protein: 24, carbs: 32, fat: 18, ingredients: ["Shrimp", "Coconut flakes", "Panko", "Sweet chili sauce"], instructions: ["Bread shrimp", "Bake until golden"], image_emoji: "🦐", color_from: "#f8fafc", color_to: "#e2e8f0" },
    { id: 95, name: "Blackened Tilapia", description: "Cajun spiced fish", cuisine: "Seafood", prep_time: 20, calories: 280, protein: 38, carbs: 4, fat: 12, ingredients: ["Tilapia", "Cajun seasoning", "Butter", "Lemon"], instructions: ["Season fish", "Sear in hot pan"], image_emoji: "🐠", color_from: "#1e293b", color_to: "#0f172a" },
    { id: 96, name: "Seafood Paella", description: "Spanish rice with seafood", cuisine: "Seafood", prep_time: 50, calories: 520, protein: 32, carbs: 58, fat: 18, ingredients: ["Rice", "Shrimp", "Mussels", "Saffron", "Peas"], instructions: ["Toast rice", "Add seafood", "Simmer"], image_emoji: "🥘", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 97, name: "Lobster Tail", description: "Butter-poached lobster", cuisine: "Seafood", prep_time: 20, calories: 380, protein: 42, carbs: 2, fat: 22, ingredients: ["Lobster tail", "Butter", "Garlic", "Lemon", "Parsley"], instructions: ["Butterfly tail", "Broil with butter"], image_emoji: "🦞", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 98, name: "Tuna Steak", description: "Seared ahi tuna", cuisine: "Seafood", prep_time: 15, calories: 320, protein: 42, carbs: 4, fat: 14, ingredients: ["Ahi tuna", "Sesame seeds", "Soy sauce", "Wasabi"], instructions: ["Coat with sesame", "Sear briefly"], image_emoji: "🍣", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 99, name: "Clam Linguine", description: "Pasta with white clam sauce", cuisine: "Seafood", prep_time: 30, calories: 480, protein: 28, carbs: 55, fat: 18, ingredients: ["Linguine", "Clams", "White wine", "Garlic", "Parsley"], instructions: ["Cook pasta", "Steam clams", "Make sauce"], image_emoji: "🐚", color_from: "#f8fafc", color_to: "#e2e8f0" },
    { id: 100, name: "Baked Salmon Teriyaki", description: "Sweet glazed salmon", cuisine: "Seafood", prep_time: 25, calories: 420, protein: 38, carbs: 22, fat: 22, ingredients: ["Salmon", "Teriyaki sauce", "Ginger", "Sesame", "Rice"], instructions: ["Marinate", "Bake", "Glaze"], image_emoji: "🐟", color_from: "#f97316", color_to: "#ea580c" },
    // === BATCH 3: BREAKFAST ===
    { id: 101, name: "Smoothie Bowl", description: "Thick smoothie with toppings", cuisine: "Breakfast", prep_time: 10, calories: 380, protein: 12, carbs: 58, fat: 12, ingredients: ["Frozen berries", "Banana", "Almond milk", "Granola", "Chia seeds"], instructions: ["Blend thick", "Top with fruit"], image_emoji: "🫐", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 102, name: "Eggs Benedict", description: "Poached eggs with hollandaise", cuisine: "Breakfast", prep_time: 30, calories: 520, protein: 24, carbs: 32, fat: 35, ingredients: ["Eggs", "English muffin", "Ham", "Hollandaise"], instructions: ["Poach eggs", "Make hollandaise", "Assemble"], image_emoji: "🍳", color_from: "#fbbf24", color_to: "#f59e0b" },
    { id: 103, name: "Breakfast Burrito", description: "Eggs and veggies wrapped", cuisine: "Breakfast", prep_time: 15, calories: 480, protein: 28, carbs: 42, fat: 24, ingredients: ["Eggs", "Tortilla", "Cheese", "Peppers", "Salsa"], instructions: ["Scramble eggs", "Add fillings", "Roll"], image_emoji: "🌯", color_from: "#f97316", color_to: "#ea580c" },
    { id: 104, name: "Steel Cut Oatmeal", description: "Hearty oats with fruit", cuisine: "Breakfast", prep_time: 25, calories: 320, protein: 10, carbs: 55, fat: 8, ingredients: ["Steel cut oats", "Milk", "Honey", "Berries", "Nuts"], instructions: ["Simmer oats", "Add toppings"], image_emoji: "🥣", color_from: "#a855f7", color_to: "#9333ea" },
    { id: 105, name: "French Toast", description: "Golden custard-soaked bread", cuisine: "Breakfast", prep_time: 20, calories: 420, protein: 14, carbs: 52, fat: 18, ingredients: ["Bread", "Eggs", "Milk", "Cinnamon", "Maple syrup"], instructions: ["Dip bread", "Pan fry", "Serve with syrup"], image_emoji: "🍞", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 106, name: "Veggie Frittata", description: "Baked Italian omelette", cuisine: "Breakfast", prep_time: 30, calories: 320, protein: 24, carbs: 12, fat: 22, ingredients: ["Eggs", "Spinach", "Tomatoes", "Cheese", "Onion"], instructions: ["Sauté veggies", "Add eggs", "Bake"], image_emoji: "🍳", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 107, name: "Chia Pudding", description: "Overnight chia seed pudding", cuisine: "Breakfast", prep_time: 5, calories: 280, protein: 10, carbs: 32, fat: 14, ingredients: ["Chia seeds", "Coconut milk", "Maple syrup", "Berries"], instructions: ["Mix and refrigerate overnight"], image_emoji: "🫐", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 108, name: "Shakshuka Eggs", description: "Eggs in spiced tomato sauce", cuisine: "Breakfast", prep_time: 25, calories: 380, protein: 22, carbs: 28, fat: 22, ingredients: ["Eggs", "Tomatoes", "Peppers", "Cumin", "Feta"], instructions: ["Make sauce", "Poach eggs in sauce"], image_emoji: "🍳", color_from: "#ef4444", color_to: "#dc2626" },
    // === MORE AMERICAN ===
    { id: 109, name: "Grilled Cheese Tomato Soup", description: "Classic comfort combo", cuisine: "American", prep_time: 25, calories: 520, protein: 18, carbs: 48, fat: 30, ingredients: ["Bread", "Cheese", "Tomato soup", "Butter"], instructions: ["Make grilled cheese", "Heat soup"], image_emoji: "🧀", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 110, name: "BLT Sandwich", description: "Bacon, lettuce, tomato on toast", cuisine: "American", prep_time: 15, calories: 420, protein: 18, carbs: 32, fat: 28, ingredients: ["Bacon", "Lettuce", "Tomato", "Mayo", "Toast"], instructions: ["Cook bacon", "Assemble sandwich"], image_emoji: "🥓", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 111, name: "Meatloaf", description: "Classic homestyle meatloaf", cuisine: "American", prep_time: 60, calories: 480, protein: 35, carbs: 28, fat: 26, ingredients: ["Ground beef", "Onion", "Breadcrumbs", "Egg", "Ketchup"], instructions: ["Mix ingredients", "Shape loaf", "Bake"], image_emoji: "🥩", color_from: "#78716c", color_to: "#57534e" },
    { id: 112, name: "Mac and Cheese", description: "Creamy baked pasta", cuisine: "American", prep_time: 35, calories: 520, protein: 22, carbs: 55, fat: 26, ingredients: ["Macaroni", "Cheddar", "Milk", "Butter", "Breadcrumbs"], instructions: ["Make cheese sauce", "Mix with pasta", "Bake"], image_emoji: "🧀", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 113, name: "Chicken Pot Pie", description: "Creamy chicken in pastry", cuisine: "American", prep_time: 50, calories: 520, protein: 28, carbs: 42, fat: 30, ingredients: ["Chicken", "Vegetables", "Cream", "Puff pastry"], instructions: ["Make filling", "Top with pastry", "Bake"], image_emoji: "🥧", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 114, name: "Pulled Pork Sandwich", description: "Slow-cooked pork with BBQ", cuisine: "American", prep_time: 240, calories: 520, protein: 32, carbs: 42, fat: 26, ingredients: ["Pork shoulder", "BBQ sauce", "Bun", "Coleslaw"], instructions: ["Slow cook pork", "Shred", "Serve on bun"], image_emoji: "🍖", color_from: "#dc2626", color_to: "#b91c1c" },
    // === WORLD CUISINES ===
    { id: 115, name: "Chicken Gyros", description: "Greek wrapped sandwich", cuisine: "Mediterranean", prep_time: 30, calories: 480, protein: 35, carbs: 42, fat: 20, ingredients: ["Chicken", "Pita", "Tzatziki", "Tomatoes", "Onion"], instructions: ["Grill chicken", "Warm pita", "Assemble"], image_emoji: "🥙", color_from: "#3b82f6", color_to: "#1d4ed8" },
    { id: 116, name: "Banh Mi", description: "Vietnamese sandwich", cuisine: "Asian", prep_time: 25, calories: 420, protein: 22, carbs: 48, fat: 18, ingredients: ["Baguette", "Pork", "Pickled vegetables", "Cilantro", "Jalapeño"], instructions: ["Toast bread", "Layer ingredients"], image_emoji: "🥖", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 117, name: "Jerk Chicken", description: "Spicy Caribbean chicken", cuisine: "Caribbean", prep_time: 45, calories: 420, protein: 42, carbs: 12, fat: 24, ingredients: ["Chicken", "Jerk seasoning", "Scotch bonnets", "Allspice", "Thyme"], instructions: ["Marinate overnight", "Grill until charred"], image_emoji: "🍗", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 118, name: "Fish and Chips", description: "British pub classic", cuisine: "British", prep_time: 35, calories: 580, protein: 32, carbs: 55, fat: 28, ingredients: ["Cod", "Potatoes", "Beer batter", "Tartar sauce"], instructions: ["Batter fish", "Fry chips", "Fry fish"], image_emoji: "🐟", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 119, name: "Pierogi", description: "Polish stuffed dumplings", cuisine: "Polish", prep_time: 60, calories: 420, protein: 14, carbs: 58, fat: 16, ingredients: ["Dough", "Potatoes", "Cheese", "Onion", "Sour cream"], instructions: ["Make dough", "Fill and seal", "Boil then fry"], image_emoji: "🥟", color_from: "#f8fafc", color_to: "#e2e8f0" },
    { id: 120, name: "Chicken Satay", description: "Thai grilled skewers", cuisine: "Asian", prep_time: 35, calories: 380, protein: 35, carbs: 18, fat: 20, ingredients: ["Chicken", "Coconut milk", "Peanut sauce", "Lime", "Cilantro"], instructions: ["Marinate", "Grill", "Serve with sauce"], image_emoji: "🍢", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 121, name: "Feijoada", description: "Brazilian black bean stew", cuisine: "Brazilian", prep_time: 120, calories: 520, protein: 32, carbs: 48, fat: 24, ingredients: ["Black beans", "Pork", "Sausage", "Orange", "Rice"], instructions: ["Slow cook beans with meat", "Serve with rice"], image_emoji: "🫘", color_from: "#1e293b", color_to: "#0f172a" },
    { id: 122, name: "Schnitzel", description: "Austrian breaded cutlet", cuisine: "German", prep_time: 25, calories: 480, protein: 38, carbs: 32, fat: 24, ingredients: ["Pork cutlet", "Breadcrumbs", "Egg", "Lemon", "Potatoes"], instructions: ["Bread cutlet", "Pan fry golden"], image_emoji: "🥩", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 123, name: "Pho Ga", description: "Vietnamese chicken soup", cuisine: "Asian", prep_time: 45, calories: 380, protein: 28, carbs: 42, fat: 12, ingredients: ["Chicken", "Rice noodles", "Ginger", "Star anise", "Herbs"], instructions: ["Make broth", "Poach chicken", "Assemble"], image_emoji: "🍜", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 124, name: "Arepas", description: "Colombian corn cakes", cuisine: "Colombian", prep_time: 30, calories: 380, protein: 18, carbs: 45, fat: 16, ingredients: ["Corn flour", "Cheese", "Butter", "Avocado", "Chicken"], instructions: ["Make dough", "Grill", "Fill"], image_emoji: "🫓", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 125, name: "Tom Yum Soup", description: "Thai hot and sour soup", cuisine: "Asian", prep_time: 25, calories: 220, protein: 22, carbs: 18, fat: 8, ingredients: ["Shrimp", "Lemongrass", "Galangal", "Lime", "Chili"], instructions: ["Make broth", "Add shrimp", "Season"], image_emoji: "🍲", color_from: "#ef4444", color_to: "#dc2626" },
    // === MORE HEALTHY OPTIONS ===
    { id: 126, name: "Zucchini Noodles", description: "Low-carb pasta alternative", cuisine: "Healthy", prep_time: 20, calories: 280, protein: 22, carbs: 18, fat: 16, ingredients: ["Zucchini", "Pesto", "Cherry tomatoes", "Parmesan", "Chicken"], instructions: ["Spiralize zucchini", "Sauté briefly", "Top with pesto"], image_emoji: "🥒", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 127, name: "Cauliflower Rice Bowl", description: "Low-carb rice substitute", cuisine: "Healthy", prep_time: 20, calories: 320, protein: 28, carbs: 18, fat: 18, ingredients: ["Cauliflower", "Chicken", "Vegetables", "Soy sauce"], instructions: ["Rice cauliflower", "Stir-fry all"], image_emoji: "🥦", color_from: "#f8fafc", color_to: "#e2e8f0" },
    { id: 128, name: "Salmon Avocado Bowl", description: "Omega-rich power bowl", cuisine: "Healthy", prep_time: 25, calories: 480, protein: 35, carbs: 28, fat: 28, ingredients: ["Salmon", "Avocado", "Quinoa", "Edamame", "Sesame"], instructions: ["Cook salmon", "Assemble bowl"], image_emoji: "🥑", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 129, name: "Turkey Meatballs", description: "Lean protein meatballs", cuisine: "Healthy", prep_time: 30, calories: 380, protein: 38, carbs: 22, fat: 16, ingredients: ["Ground turkey", "Zucchini", "Herbs", "Marinara"], instructions: ["Form balls", "Bake", "Serve with sauce"], image_emoji: "🧆", color_from: "#78716c", color_to: "#57534e" },
    { id: 130, name: "Lemon Herb Chicken Salad", description: "Light and refreshing", cuisine: "Healthy", prep_time: 20, calories: 320, protein: 35, carbs: 12, fat: 16, ingredients: ["Chicken breast", "Mixed greens", "Lemon", "Herbs", "Olive oil"], instructions: ["Grill chicken", "Toss salad"], image_emoji: "🥗", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 131, name: "Stuffed Sweet Potato", description: "Loaded with protein", cuisine: "Healthy", prep_time: 45, calories: 420, protein: 28, carbs: 48, fat: 14, ingredients: ["Sweet potato", "Black beans", "Cheese", "Salsa", "Greek yogurt"], instructions: ["Bake potato", "Fill with toppings"], image_emoji: "🍠", color_from: "#f97316", color_to: "#ea580c" },
    { id: 132, name: "Egg Muffins", description: "Portable protein breakfast", cuisine: "Healthy", prep_time: 25, calories: 180, protein: 18, carbs: 6, fat: 10, ingredients: ["Eggs", "Spinach", "Peppers", "Cheese"], instructions: ["Mix ingredients", "Bake in muffin tin"], image_emoji: "🧁", color_from: "#fbbf24", color_to: "#f59e0b" },
    { id: 133, name: "Grilled Shrimp Skewers", description: "Light seafood dinner", cuisine: "Healthy", prep_time: 20, calories: 220, protein: 32, carbs: 8, fat: 8, ingredients: ["Shrimp", "Garlic", "Lemon", "Olive oil", "Herbs"], instructions: ["Thread on skewers", "Grill 3 min each side"], image_emoji: "🦐", color_from: "#ec4899", color_to: "#db2777" },
    { id: 134, name: "Mediterranean Plate", description: "Mezze-style platter", cuisine: "Mediterranean", prep_time: 20, calories: 420, protein: 18, carbs: 42, fat: 22, ingredients: ["Hummus", "Falafel", "Olives", "Feta", "Pita"], instructions: ["Arrange on plate"], image_emoji: "🫒", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 135, name: "Asian Lettuce Cups", description: "Crunchy and fresh", cuisine: "Asian", prep_time: 20, calories: 280, protein: 24, carbs: 18, fat: 14, ingredients: ["Ground chicken", "Water chestnuts", "Lettuce", "Hoisin", "Ginger"], instructions: ["Cook filling", "Serve in lettuce"], image_emoji: "🥬", color_from: "#84cc16", color_to: "#65a30d" },
    // === MORE VARIETY ===
    { id: 136, name: "Pesto Chicken Pasta", description: "Basil pesto with chicken", cuisine: "Italian", prep_time: 25, calories: 520, protein: 38, carbs: 48, fat: 22, ingredients: ["Pasta", "Chicken", "Pesto", "Cherry tomatoes", "Parmesan"], instructions: ["Cook pasta", "Grill chicken", "Toss with pesto"], image_emoji: "🍝", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 137, name: "Lamb Souvlaki", description: "Greek grilled lamb", cuisine: "Mediterranean", prep_time: 35, calories: 480, protein: 38, carbs: 28, fat: 26, ingredients: ["Lamb", "Lemon", "Oregano", "Pita", "Tzatziki"], instructions: ["Marinate lamb", "Grill", "Serve with pita"], image_emoji: "🍖", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 138, name: "Kung Pao Chicken", description: "Spicy Sichuan chicken", cuisine: "Asian", prep_time: 25, calories: 420, protein: 35, carbs: 28, fat: 20, ingredients: ["Chicken", "Peanuts", "Dried chilies", "Soy sauce", "Rice"], instructions: ["Stir-fry chicken", "Add sauce and peanuts"], image_emoji: "🥜", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 139, name: "Greek Salad", description: "Classic Mediterranean salad", cuisine: "Mediterranean", prep_time: 15, calories: 280, protein: 10, carbs: 18, fat: 20, ingredients: ["Cucumber", "Tomatoes", "Olives", "Feta", "Red onion"], instructions: ["Chop vegetables", "Toss with olive oil"], image_emoji: "🥒", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 140, name: "Beef Pho", description: "Vietnamese beef noodle soup", cuisine: "Asian", prep_time: 60, calories: 420, protein: 32, carbs: 48, fat: 14, ingredients: ["Beef", "Rice noodles", "Beef broth", "Herbs", "Bean sprouts"], instructions: ["Simmer broth", "Cook noodles", "Assemble"], image_emoji: "🍜", color_from: "#78716c", color_to: "#57534e" },
    { id: 141, name: "Huevos Rancheros", description: "Mexican breakfast eggs", cuisine: "Mexican", prep_time: 25, calories: 420, protein: 22, carbs: 38, fat: 22, ingredients: ["Eggs", "Tortillas", "Black beans", "Salsa", "Avocado"], instructions: ["Fry eggs", "Warm beans", "Assemble"], image_emoji: "🍳", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 142, name: "Minestrone Soup", description: "Italian vegetable soup", cuisine: "Italian", prep_time: 40, calories: 280, protein: 12, carbs: 42, fat: 8, ingredients: ["Vegetables", "Beans", "Pasta", "Tomatoes", "Herbs"], instructions: ["Sauté vegetables", "Add broth", "Simmer"], image_emoji: "🍲", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 143, name: "Grilled Lamb Chops", description: "Herb-crusted lamb", cuisine: "Mediterranean", prep_time: 25, calories: 480, protein: 38, carbs: 8, fat: 34, ingredients: ["Lamb chops", "Rosemary", "Garlic", "Olive oil", "Mint"], instructions: ["Season", "Grill 4 min each side"], image_emoji: "🥩", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 144, name: "Vegetable Stir-Fry", description: "Quick veggie dinner", cuisine: "Asian", prep_time: 15, calories: 220, protein: 8, carbs: 32, fat: 10, ingredients: ["Mixed vegetables", "Soy sauce", "Garlic", "Ginger", "Rice"], instructions: ["Stir-fry vegetables", "Add sauce"], image_emoji: "🥦", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 145, name: "Chicken Parmesan", description: "Breaded chicken with cheese", cuisine: "Italian", prep_time: 35, calories: 520, protein: 42, carbs: 32, fat: 26, ingredients: ["Chicken breast", "Breadcrumbs", "Marinara", "Mozzarella", "Parmesan"], instructions: ["Bread chicken", "Fry", "Top with sauce and cheese"], image_emoji: "🍗", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 146, name: "Seared Scallops", description: "Pan-seared sea scallops", cuisine: "Seafood", prep_time: 15, calories: 280, protein: 28, carbs: 12, fat: 14, ingredients: ["Scallops", "Butter", "Garlic", "Lemon", "Capers"], instructions: ["Dry scallops", "Sear 2 min each side"], image_emoji: "🐚", color_from: "#f8fafc", color_to: "#e2e8f0" },
    { id: 147, name: "Chicken Cacciatore", description: "Italian braised chicken", cuisine: "Italian", prep_time: 45, calories: 420, protein: 38, carbs: 22, fat: 22, ingredients: ["Chicken", "Tomatoes", "Peppers", "Olives", "Wine"], instructions: ["Brown chicken", "Add vegetables", "Braise"], image_emoji: "🍗", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 148, name: "Teriyaki Tofu", description: "Glazed tofu with vegetables", cuisine: "Asian", prep_time: 25, calories: 320, protein: 18, carbs: 35, fat: 14, ingredients: ["Tofu", "Teriyaki sauce", "Broccoli", "Rice", "Sesame"], instructions: ["Press tofu", "Pan fry", "Glaze"], image_emoji: "🥢", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 149, name: "Beef Tacos", description: "Classic ground beef tacos", cuisine: "Mexican", prep_time: 20, calories: 420, protein: 28, carbs: 35, fat: 22, ingredients: ["Ground beef", "Taco seasoning", "Tortillas", "Cheese", "Lettuce"], instructions: ["Brown beef", "Season", "Assemble"], image_emoji: "🌮", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 150, name: "Shrimp Scampi", description: "Garlic butter shrimp pasta", cuisine: "Italian", prep_time: 20, calories: 480, protein: 32, carbs: 48, fat: 20, ingredients: ["Shrimp", "Linguine", "Garlic", "White wine", "Lemon"], instructions: ["Cook pasta", "Sauté shrimp", "Toss together"], image_emoji: "🦐", color_from: "#f97316", color_to: "#ea580c" },
    // === BATCH 4: FINAL 60 MEALS ===
    { id: 151, name: "Spaghetti Carbonara", description: "Creamy bacon pasta", cuisine: "Italian", prep_time: 25, calories: 520, protein: 24, carbs: 55, fat: 24, ingredients: ["Spaghetti", "Bacon", "Eggs", "Parmesan", "Black pepper"], instructions: ["Cook pasta", "Fry bacon", "Mix eggs and cheese", "Combine"], image_emoji: "🍝", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 152, name: "Chicken Alfredo", description: "Creamy garlic pasta", cuisine: "Italian", prep_time: 30, calories: 580, protein: 42, carbs: 48, fat: 28, ingredients: ["Fettuccine", "Chicken", "Cream", "Parmesan", "Garlic"], instructions: ["Cook pasta", "Make sauce", "Add chicken"], image_emoji: "🍝", color_from: "#f8fafc", color_to: "#e2e8f0" },
    { id: 153, name: "Sesame Ginger Salmon", description: "Asian glazed salmon", cuisine: "Asian", prep_time: 25, calories: 420, protein: 38, carbs: 18, fat: 24, ingredients: ["Salmon", "Sesame oil", "Ginger", "Soy sauce", "Honey"], instructions: ["Make glaze", "Bake salmon", "Drizzle"], image_emoji: "🐟", color_from: "#f97316", color_to: "#ea580c" },
    { id: 154, name: "Moroccan Couscous", description: "Spiced couscous with vegetables", cuisine: "Moroccan", prep_time: 25, calories: 380, protein: 14, carbs: 58, fat: 12, ingredients: ["Couscous", "Chickpeas", "Vegetables", "Harissa", "Herbs"], instructions: ["Steam couscous", "Roast vegetables", "Combine"], image_emoji: "🥘", color_from: "#f97316", color_to: "#ea580c" },
    { id: 155, name: "Beef Bulgogi", description: "Korean marinated beef", cuisine: "Asian", prep_time: 35, calories: 480, protein: 38, carbs: 35, fat: 22, ingredients: ["Beef", "Soy sauce", "Pear", "Sesame", "Rice"], instructions: ["Marinate beef", "Grill", "Serve with rice"], image_emoji: "🥩", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 156, name: "Vegetable Lasagna", description: "Layered pasta with veggies", cuisine: "Vegetarian", prep_time: 60, calories: 420, protein: 20, carbs: 48, fat: 18, ingredients: ["Lasagna noodles", "Ricotta", "Spinach", "Zucchini", "Marinara"], instructions: ["Layer ingredients", "Bake 45 min"], image_emoji: "🍝", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 157, name: "Honey Mustard Chicken", description: "Sweet tangy glazed chicken", cuisine: "American", prep_time: 30, calories: 420, protein: 42, carbs: 22, fat: 18, ingredients: ["Chicken", "Honey", "Mustard", "Garlic", "Thyme"], instructions: ["Make glaze", "Coat chicken", "Bake"], image_emoji: "🍯", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 158, name: "Shrimp Pad See Ew", description: "Thai wide noodles", cuisine: "Asian", prep_time: 25, calories: 480, protein: 28, carbs: 52, fat: 18, ingredients: ["Wide rice noodles", "Shrimp", "Chinese broccoli", "Soy sauce", "Egg"], instructions: ["Cook noodles", "Stir-fry all"], image_emoji: "🍜", color_from: "#78716c", color_to: "#57534e" },
    { id: 159, name: "Mediterranean Wrap", description: "Fresh veggie wrap", cuisine: "Mediterranean", prep_time: 15, calories: 380, protein: 16, carbs: 42, fat: 18, ingredients: ["Wrap", "Hummus", "Feta", "Cucumber", "Tomatoes"], instructions: ["Spread hummus", "Add fillings", "Roll"], image_emoji: "🌯", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 160, name: "Pork Tenderloin", description: "Roasted with herbs", cuisine: "American", prep_time: 40, calories: 380, protein: 42, carbs: 8, fat: 20, ingredients: ["Pork tenderloin", "Rosemary", "Garlic", "Olive oil", "Potatoes"], instructions: ["Season", "Roast", "Rest and slice"], image_emoji: "🍖", color_from: "#f97316", color_to: "#ea580c" },
    { id: 161, name: "Greek Stuffed Peppers", description: "Peppers with rice and feta", cuisine: "Mediterranean", prep_time: 45, calories: 380, protein: 14, carbs: 42, fat: 18, ingredients: ["Bell peppers", "Rice", "Feta", "Tomatoes", "Herbs"], instructions: ["Cook filling", "Stuff peppers", "Bake"], image_emoji: "🫑", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 162, name: "Chicken Korma", description: "Mild creamy curry", cuisine: "Indian", prep_time: 40, calories: 480, protein: 35, carbs: 28, fat: 28, ingredients: ["Chicken", "Yogurt", "Cream", "Almonds", "Spices"], instructions: ["Brown chicken", "Make sauce", "Simmer"], image_emoji: "🍛", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 163, name: "Black Bean Burgers", description: "Vegetarian patties", cuisine: "Vegetarian", prep_time: 25, calories: 380, protein: 18, carbs: 48, fat: 14, ingredients: ["Black beans", "Oats", "Onion", "Spices", "Bun"], instructions: ["Mash beans", "Form patties", "Pan fry"], image_emoji: "🍔", color_from: "#1e293b", color_to: "#0f172a" },
    { id: 164, name: "Salmon Cakes", description: "Pan-fried salmon patties", cuisine: "Seafood", prep_time: 25, calories: 320, protein: 28, carbs: 18, fat: 16, ingredients: ["Salmon", "Breadcrumbs", "Egg", "Dill", "Lemon"], instructions: ["Mix ingredients", "Form patties", "Pan fry"], image_emoji: "🐟", color_from: "#f97316", color_to: "#ea580c" },
    { id: 165, name: "Thai Green Curry", description: "Coconut curry with vegetables", cuisine: "Asian", prep_time: 30, calories: 420, protein: 22, carbs: 32, fat: 26, ingredients: ["Green curry paste", "Coconut milk", "Chicken", "Vegetables", "Thai basil"], instructions: ["Fry paste", "Add coconut milk", "Simmer with chicken"], image_emoji: "🍛", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 166, name: "Quinoa Stuffed Peppers", description: "Protein-packed stuffed peppers", cuisine: "Healthy", prep_time: 45, calories: 380, protein: 18, carbs: 45, fat: 14, ingredients: ["Bell peppers", "Quinoa", "Black beans", "Corn", "Cheese"], instructions: ["Cook quinoa", "Mix filling", "Stuff and bake"], image_emoji: "🫑", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 167, name: "Lemon Garlic Shrimp", description: "Mediterranean-style shrimp", cuisine: "Mediterranean", prep_time: 15, calories: 280, protein: 32, carbs: 8, fat: 14, ingredients: ["Shrimp", "Garlic", "Lemon", "Olive oil", "Parsley"], instructions: ["Sauté garlic", "Add shrimp", "Finish with lemon"], image_emoji: "🦐", color_from: "#fbbf24", color_to: "#f59e0b" },
    { id: 168, name: "Chicken Marsala", description: "Wine-braised chicken", cuisine: "Italian", prep_time: 35, calories: 420, protein: 40, carbs: 18, fat: 22, ingredients: ["Chicken", "Marsala wine", "Mushrooms", "Cream", "Herbs"], instructions: ["Sear chicken", "Make sauce", "Combine"], image_emoji: "🍗", color_from: "#78716c", color_to: "#57534e" },
    { id: 169, name: "Sweet and Sour Pork", description: "Classic Chinese dish", cuisine: "Asian", prep_time: 35, calories: 480, protein: 28, carbs: 52, fat: 18, ingredients: ["Pork", "Pineapple", "Bell peppers", "Sweet sour sauce", "Rice"], instructions: ["Batter pork", "Fry", "Toss in sauce"], image_emoji: "🍍", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 170, name: "Tuscan White Bean Soup", description: "Italian bean soup", cuisine: "Italian", prep_time: 35, calories: 320, protein: 16, carbs: 48, fat: 10, ingredients: ["White beans", "Kale", "Tomatoes", "Garlic", "Broth"], instructions: ["Sauté aromatics", "Add beans", "Simmer"], image_emoji: "🍲", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 171, name: "Beef Bourguignon", description: "French beef stew", cuisine: "French", prep_time: 120, calories: 520, protein: 38, carbs: 32, fat: 28, ingredients: ["Beef", "Red wine", "Mushrooms", "Pearl onions", "Carrots"], instructions: ["Brown beef", "Add wine", "Braise slowly"], image_emoji: "🍷", color_from: "#7c3aed", color_to: "#6d28d9" },
    { id: 172, name: "Vegetable Curry", description: "Mixed veggie coconut curry", cuisine: "Indian", prep_time: 30, calories: 320, protein: 10, carbs: 42, fat: 14, ingredients: ["Mixed vegetables", "Coconut milk", "Curry powder", "Rice", "Cilantro"], instructions: ["Sauté vegetables", "Add spices and coconut milk", "Simmer"], image_emoji: "🍛", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 173, name: "Chicken Piccata", description: "Lemon caper chicken", cuisine: "Italian", prep_time: 25, calories: 380, protein: 38, carbs: 12, fat: 20, ingredients: ["Chicken", "Lemon", "Capers", "White wine", "Butter"], instructions: ["Pound chicken", "Pan fry", "Make caper sauce"], image_emoji: "🍋", color_from: "#fbbf24", color_to: "#f59e0b" },
    { id: 174, name: "Bibim Guksu", description: "Korean spicy cold noodles", cuisine: "Asian", prep_time: 20, calories: 380, protein: 14, carbs: 62, fat: 10, ingredients: ["Thin noodles", "Gochujang", "Cucumber", "Egg", "Sesame"], instructions: ["Cook noodles", "Make sauce", "Toss cold"], image_emoji: "🍜", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 175, name: "Stuffed Zucchini Boats", description: "Zucchini with meat filling", cuisine: "Mediterranean", prep_time: 40, calories: 320, protein: 28, carbs: 18, fat: 18, ingredients: ["Zucchini", "Ground turkey", "Tomatoes", "Cheese", "Herbs"], instructions: ["Hollow zucchini", "Fill with mixture", "Bake"], image_emoji: "🥒", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 176, name: "Chicken Souvlaki", description: "Greek grilled chicken", cuisine: "Mediterranean", prep_time: 30, calories: 380, protein: 40, carbs: 22, fat: 16, ingredients: ["Chicken", "Lemon", "Oregano", "Garlic", "Yogurt"], instructions: ["Marinate", "Grill", "Serve with tzatziki"], image_emoji: "🍢", color_from: "#3b82f6", color_to: "#1d4ed8" },
    { id: 177, name: "Cajun Jambalaya", description: "Louisiana rice dish", cuisine: "American", prep_time: 45, calories: 520, protein: 32, carbs: 52, fat: 22, ingredients: ["Rice", "Sausage", "Shrimp", "Chicken", "Cajun spices"], instructions: ["Sauté meats", "Add rice and broth", "Simmer"], image_emoji: "🦐", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 178, name: "Mushroom Stroganoff", description: "Vegetarian stroganoff", cuisine: "Vegetarian", prep_time: 30, calories: 380, protein: 12, carbs: 48, fat: 18, ingredients: ["Mushrooms", "Sour cream", "Onion", "Pasta", "Thyme"], instructions: ["Sauté mushrooms", "Add cream", "Toss with pasta"], image_emoji: "🍄", color_from: "#78716c", color_to: "#57534e" },
    { id: 179, name: "Lemon Herb Tilapia", description: "Light baked fish", cuisine: "Seafood", prep_time: 20, calories: 280, protein: 36, carbs: 6, fat: 12, ingredients: ["Tilapia", "Lemon", "Herbs", "Garlic", "Olive oil"], instructions: ["Season fish", "Bake 15 min"], image_emoji: "🐠", color_from: "#fbbf24", color_to: "#f59e0b" },
    { id: 180, name: "Lamb Tagine", description: "Moroccan slow-cooked lamb", cuisine: "Moroccan", prep_time: 90, calories: 480, protein: 35, carbs: 38, fat: 24, ingredients: ["Lamb", "Apricots", "Almonds", "Spices", "Couscous"], instructions: ["Brown lamb", "Add spices and fruit", "Slow cook"], image_emoji: "🫕", color_from: "#f97316", color_to: "#ea580c" },
    { id: 181, name: "Crispy Tofu Buddha Bowl", description: "Vegan power bowl", cuisine: "Vegetarian", prep_time: 35, calories: 420, protein: 22, carbs: 48, fat: 18, ingredients: ["Tofu", "Brown rice", "Edamame", "Avocado", "Tahini"], instructions: ["Bake tofu", "Assemble bowl"], image_emoji: "🥗", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 182, name: "Chicken Vindaloo", description: "Spicy Goan curry", cuisine: "Indian", prep_time: 45, calories: 420, protein: 38, carbs: 22, fat: 22, ingredients: ["Chicken", "Vinegar", "Chilies", "Spices", "Potatoes"], instructions: ["Marinate", "Cook slowly"], image_emoji: "🌶️", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 183, name: "Mango Sticky Rice", description: "Thai sweet dessert", cuisine: "Asian", prep_time: 40, calories: 380, protein: 6, carbs: 72, fat: 10, ingredients: ["Glutinous rice", "Coconut milk", "Mango", "Sugar"], instructions: ["Steam rice", "Add coconut milk", "Serve with mango"], image_emoji: "🥭", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 184, name: "Avocado Chicken Salad", description: "Creamy chicken salad", cuisine: "Healthy", prep_time: 15, calories: 380, protein: 35, carbs: 12, fat: 24, ingredients: ["Chicken", "Avocado", "Lime", "Cilantro", "Red onion"], instructions: ["Shred chicken", "Mash avocado", "Mix all"], image_emoji: "🥑", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 185, name: "Gnocchi with Sage Butter", description: "Italian potato pasta", cuisine: "Italian", prep_time: 25, calories: 420, protein: 12, carbs: 55, fat: 18, ingredients: ["Gnocchi", "Butter", "Sage", "Parmesan", "Garlic"], instructions: ["Boil gnocchi", "Make sage butter", "Toss"], image_emoji: "🥟", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 186, name: "Hawaiian Poke", description: "Fresh fish rice bowl", cuisine: "Asian", prep_time: 20, calories: 420, protein: 28, carbs: 48, fat: 14, ingredients: ["Ahi tuna", "Sushi rice", "Soy sauce", "Sesame", "Seaweed"], instructions: ["Marinate tuna", "Assemble bowl"], image_emoji: "🐟", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 187, name: "Chimichurri Steak", description: "Argentine herb steak", cuisine: "Argentinian", prep_time: 25, calories: 480, protein: 42, carbs: 8, fat: 32, ingredients: ["Steak", "Parsley", "Oregano", "Garlic", "Olive oil"], instructions: ["Make chimichurri", "Grill steak", "Top with sauce"], image_emoji: "🥩", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 188, name: "Lentil Bolognese", description: "Vegetarian meat sauce", cuisine: "Vegetarian", prep_time: 40, calories: 380, protein: 18, carbs: 55, fat: 10, ingredients: ["Lentils", "Tomatoes", "Pasta", "Carrots", "Celery"], instructions: ["Cook lentils", "Make sauce", "Serve with pasta"], image_emoji: "🍝", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 189, name: "Bruschetta Chicken", description: "Italian topped chicken", cuisine: "Italian", prep_time: 30, calories: 380, protein: 42, carbs: 12, fat: 18, ingredients: ["Chicken", "Tomatoes", "Basil", "Garlic", "Balsamic"], instructions: ["Grill chicken", "Make topping", "Assemble"], image_emoji: "🍅", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 190, name: "Dan Dan Noodles", description: "Sichuan spicy noodles", cuisine: "Asian", prep_time: 25, calories: 480, protein: 22, carbs: 52, fat: 22, ingredients: ["Noodles", "Pork", "Chili oil", "Soy sauce", "Peanuts"], instructions: ["Cook noodles", "Make sauce", "Top with pork"], image_emoji: "🍜", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 191, name: "Chicken Milanese", description: "Crispy breaded chicken", cuisine: "Italian", prep_time: 25, calories: 420, protein: 40, carbs: 28, fat: 20, ingredients: ["Chicken", "Breadcrumbs", "Parmesan", "Arugula", "Lemon"], instructions: ["Bread chicken", "Pan fry", "Top with salad"], image_emoji: "🍗", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 192, name: "Vegetable Tempura", description: "Light battered veggies", cuisine: "Asian", prep_time: 30, calories: 320, protein: 8, carbs: 42, fat: 14, ingredients: ["Mixed vegetables", "Tempura batter", "Dipping sauce"], instructions: ["Make batter", "Fry vegetables"], image_emoji: "🥦", color_from: "#fbbf24", color_to: "#f59e0b" },
    { id: 193, name: "Shakshuka with Feta", description: "Enhanced Israeli eggs", cuisine: "Mediterranean", prep_time: 25, calories: 380, protein: 24, carbs: 22, fat: 24, ingredients: ["Eggs", "Tomatoes", "Feta", "Peppers", "Cumin"], instructions: ["Make tomato sauce", "Add eggs and feta", "Bake"], image_emoji: "🍳", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 194, name: "Coconut Curry Chicken", description: "Thai-inspired curry", cuisine: "Asian", prep_time: 35, calories: 480, protein: 38, carbs: 28, fat: 26, ingredients: ["Chicken", "Coconut milk", "Curry paste", "Bamboo shoots", "Thai basil"], instructions: ["Cook curry paste", "Add coconut milk", "Simmer chicken"], image_emoji: "🍛", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 195, name: "Stuffed Mushrooms", description: "Cheesy baked mushrooms", cuisine: "American", prep_time: 30, calories: 280, protein: 14, carbs: 18, fat: 18, ingredients: ["Mushrooms", "Cream cheese", "Parmesan", "Garlic", "Herbs"], instructions: ["Remove stems", "Fill caps", "Bake"], image_emoji: "🍄", color_from: "#78716c", color_to: "#57534e" },
    { id: 196, name: "Mahi Mahi Tacos", description: "Grilled fish tacos", cuisine: "Mexican", prep_time: 25, calories: 380, protein: 32, carbs: 35, fat: 14, ingredients: ["Mahi mahi", "Tortillas", "Cabbage", "Lime crema", "Cilantro"], instructions: ["Grill fish", "Assemble tacos"], image_emoji: "🌮", color_from: "#14b8a6", color_to: "#0d9488" },
    { id: 197, name: "Eggplant Rollatini", description: "Stuffed eggplant rolls", cuisine: "Italian", prep_time: 45, calories: 380, protein: 18, carbs: 28, fat: 24, ingredients: ["Eggplant", "Ricotta", "Marinara", "Mozzarella", "Basil"], instructions: ["Slice and grill eggplant", "Roll with filling", "Bake"], image_emoji: "🍆", color_from: "#8b5cf6", color_to: "#7c3aed" },
    { id: 198, name: "Chicken Adobo", description: "Filipino braised chicken", cuisine: "Asian", prep_time: 45, calories: 420, protein: 40, carbs: 18, fat: 22, ingredients: ["Chicken", "Soy sauce", "Vinegar", "Garlic", "Bay leaves"], instructions: ["Brown chicken", "Add liquids", "Braise"], image_emoji: "🍗", color_from: "#78716c", color_to: "#57534e" },
    { id: 199, name: "Spinach Salad", description: "Fresh spinach with toppings", cuisine: "Salads", prep_time: 15, calories: 320, protein: 12, carbs: 18, fat: 24, ingredients: ["Spinach", "Bacon", "Mushrooms", "Egg", "Balsamic"], instructions: ["Toss ingredients", "Drizzle dressing"], image_emoji: "🥗", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 200, name: "Beef Rendang", description: "Indonesian coconut beef", cuisine: "Asian", prep_time: 120, calories: 520, protein: 38, carbs: 18, fat: 34, ingredients: ["Beef", "Coconut milk", "Lemongrass", "Galangal", "Spices"], instructions: ["Brown beef", "Add spices and coconut", "Slow cook"], image_emoji: "🥘", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 201, name: "Baked Ziti", description: "Cheesy pasta bake", cuisine: "Italian", prep_time: 45, calories: 520, protein: 28, carbs: 55, fat: 22, ingredients: ["Ziti", "Ricotta", "Marinara", "Mozzarella", "Parmesan"], instructions: ["Cook pasta", "Layer with cheese", "Bake"], image_emoji: "🍝", color_from: "#ef4444", color_to: "#dc2626" },
    { id: 202, name: "Honey Garlic Salmon", description: "Sweet glazed salmon", cuisine: "Seafood", prep_time: 25, calories: 420, protein: 38, carbs: 22, fat: 22, ingredients: ["Salmon", "Honey", "Garlic", "Soy sauce", "Ginger"], instructions: ["Make glaze", "Bake salmon"], image_emoji: "🐟", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 203, name: "Fajita Vegetables", description: "Sizzling vegetarian fajitas", cuisine: "Mexican", prep_time: 20, calories: 280, protein: 8, carbs: 35, fat: 14, ingredients: ["Bell peppers", "Onions", "Fajita seasoning", "Tortillas", "Guacamole"], instructions: ["Slice vegetables", "Sauté hot", "Serve in tortillas"], image_emoji: "🌮", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 204, name: "Chicken Lettuce Wraps", description: "Asian-style wraps", cuisine: "Asian", prep_time: 20, calories: 280, protein: 28, carbs: 18, fat: 12, ingredients: ["Chicken", "Lettuce", "Water chestnuts", "Hoisin", "Ginger"], instructions: ["Cook filling", "Wrap in lettuce"], image_emoji: "🥬", color_from: "#84cc16", color_to: "#65a30d" },
    { id: 205, name: "Seafood Risotto", description: "Creamy rice with seafood", cuisine: "Italian", prep_time: 45, calories: 520, protein: 32, carbs: 55, fat: 20, ingredients: ["Arborio rice", "Shrimp", "Scallops", "White wine", "Parmesan"], instructions: ["Toast rice", "Add broth slowly", "Finish with seafood"], image_emoji: "🦐", color_from: "#f97316", color_to: "#ea580c" },
    { id: 206, name: "Chicken Tinga", description: "Mexican shredded chicken", cuisine: "Mexican", prep_time: 35, calories: 380, protein: 35, carbs: 28, fat: 16, ingredients: ["Chicken", "Chipotle", "Tomatoes", "Onion", "Tostadas"], instructions: ["Poach and shred chicken", "Make sauce", "Combine"], image_emoji: "🌮", color_from: "#dc2626", color_to: "#b91c1c" },
    { id: 207, name: "Grilled Asparagus", description: "Simple charred asparagus", cuisine: "Healthy", prep_time: 15, calories: 120, protein: 5, carbs: 8, fat: 10, ingredients: ["Asparagus", "Olive oil", "Lemon", "Parmesan", "Garlic"], instructions: ["Toss with oil", "Grill until charred"], image_emoji: "🥬", color_from: "#22c55e", color_to: "#16a34a" },
    { id: 208, name: "Beef Empanadas", description: "Savory meat pastries", cuisine: "Argentinian", prep_time: 50, calories: 420, protein: 22, carbs: 38, fat: 22, ingredients: ["Ground beef", "Pastry", "Olives", "Egg", "Cumin"], instructions: ["Make filling", "Fill pastry", "Bake"], image_emoji: "🥟", color_from: "#f59e0b", color_to: "#d97706" },
    { id: 209, name: "Miso Glazed Eggplant", description: "Japanese sweet miso eggplant", cuisine: "Asian", prep_time: 30, calories: 280, protein: 8, carbs: 32, fat: 14, ingredients: ["Eggplant", "White miso", "Mirin", "Sesame", "Green onion"], instructions: ["Score eggplant", "Broil with glaze"], image_emoji: "🍆", color_from: "#a855f7", color_to: "#9333ea" },
    { id: 210, name: "Grilled Chicken Kebabs", description: "Marinated chicken skewers", cuisine: "Mediterranean", prep_time: 30, calories: 320, protein: 38, carbs: 12, fat: 14, ingredients: ["Chicken", "Bell peppers", "Onion", "Lemon", "Herbs"], instructions: ["Marinate chicken", "Thread on skewers", "Grill"], image_emoji: "🍢", color_from: "#f97316", color_to: "#ea580c" }
];

// Helper function to group meals by cuisine
export function getMealsByCuisine(): Record<string, MealPlan[]> {
    return mealPlans.reduce((acc, meal) => {
        if (!acc[meal.cuisine]) {
            acc[meal.cuisine] = [];
        }
        acc[meal.cuisine].push(meal);
        return acc;
    }, {} as Record<string, MealPlan[]>);
}

// Get random meals for variety
export function getRandomMeals(count: number): MealPlan[] {
    const shuffled = [...mealPlans].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}
