import { MealPlan } from './types';

// 50+ International Meal Plans
export const mealPlans: MealPlan[] = [
    // === MEDITERRANEAN ===
    {
        id: 1,
        name: "Greek Chicken Bowl",
        description: "Grilled chicken with cucumber, tomatoes, feta, and tzatziki",
        cuisine: "Mediterranean",
        prep_time: 25,
        calories: 450,
        protein: 42,
        carbs: 28,
        fat: 18,
        ingredients: ["300g chicken breast", "100g cucumber", "100g tomatoes", "30g feta", "50g tzatziki", "100g rice"],
        instructions: ["Grill seasoned chicken", "Dice vegetables", "Cook rice", "Assemble bowl with tzatziki"],
        image_emoji: "🥗",
        color_from: "#3b82f6",
        color_to: "#1d4ed8"
    },
    {
        id: 2,
        name: "Shakshuka",
        description: "Eggs poached in spiced tomato sauce with peppers",
        cuisine: "Mediterranean",
        prep_time: 20,
        calories: 380,
        protein: 24,
        carbs: 22,
        fat: 22,
        ingredients: ["4 eggs", "400g canned tomatoes", "1 bell pepper", "1 onion", "Cumin, paprika", "Fresh parsley"],
        instructions: ["Sauté onion and pepper", "Add tomatoes and spices", "Make wells and crack eggs", "Cover and cook until set"],
        image_emoji: "🍳",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 3,
        name: "Grilled Salmon with Lemon",
        description: "Fresh salmon with herbs, lemon, and roasted vegetables",
        cuisine: "Mediterranean",
        prep_time: 30,
        calories: 480,
        protein: 38,
        carbs: 20,
        fat: 28,
        ingredients: ["200g salmon fillet", "200g mixed vegetables", "1 lemon", "Olive oil", "Fresh dill"],
        instructions: ["Season salmon with herbs", "Roast vegetables", "Grill salmon 4 min each side", "Serve with lemon"],
        image_emoji: "🐟",
        color_from: "#f97316",
        color_to: "#ea580c"
    },

    // === ASIAN ===
    {
        id: 4,
        name: "Beef Teriyaki Bowl",
        description: "Tender beef strips with teriyaki glaze over rice",
        cuisine: "Asian",
        prep_time: 30,
        calories: 520,
        protein: 38,
        carbs: 45,
        fat: 20,
        ingredients: ["200g beef sirloin", "150g rice", "100g broccoli", "Teriyaki sauce", "Sesame seeds"],
        instructions: ["Slice beef thin", "Stir-fry on high heat", "Add teriyaki sauce", "Serve over rice with broccoli"],
        image_emoji: "🍜",
        color_from: "#f59e0b",
        color_to: "#d97706"
    },
    {
        id: 5,
        name: "Chicken Stir-Fry",
        description: "Quick chicken with vegetables in savory sauce",
        cuisine: "Asian",
        prep_time: 20,
        calories: 420,
        protein: 40,
        carbs: 30,
        fat: 16,
        ingredients: ["250g chicken breast", "200g mixed vegetables", "Soy sauce", "Ginger", "Garlic", "100g rice"],
        instructions: ["Cut chicken into pieces", "Stir-fry vegetables first", "Add chicken and sauce", "Serve with rice"],
        image_emoji: "🥢",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    {
        id: 6,
        name: "Shrimp Fried Rice",
        description: "Classic fried rice loaded with shrimp and vegetables",
        cuisine: "Asian",
        prep_time: 25,
        calories: 480,
        protein: 32,
        carbs: 52,
        fat: 16,
        ingredients: ["200g shrimp", "200g cooked rice", "2 eggs", "100g peas", "Soy sauce", "Green onions"],
        instructions: ["Scramble eggs, set aside", "Fry shrimp until pink", "Add cold rice and vegetables", "Mix in eggs and soy sauce"],
        image_emoji: "🍤",
        color_from: "#06b6d4",
        color_to: "#0891b2"
    },
    {
        id: 7,
        name: "Thai Basil Chicken",
        description: "Spicy ground chicken with Thai basil and chilies",
        cuisine: "Asian",
        prep_time: 15,
        calories: 440,
        protein: 38,
        carbs: 35,
        fat: 18,
        ingredients: ["250g ground chicken", "Thai basil leaves", "2 chilies", "Garlic", "Fish sauce", "150g rice"],
        instructions: ["Fry garlic and chilies", "Add chicken, break apart", "Season with fish sauce", "Toss with basil, serve over rice"],
        image_emoji: "🌶️",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },

    // === MEXICAN ===
    {
        id: 8,
        name: "Chicken Fajita Bowl",
        description: "Sizzling chicken with peppers and Mexican rice",
        cuisine: "Mexican",
        prep_time: 25,
        calories: 480,
        protein: 45,
        carbs: 35,
        fat: 18,
        ingredients: ["250g chicken breast", "2 bell peppers", "1 onion", "Fajita seasoning", "100g rice", "Salsa"],
        instructions: ["Slice chicken and vegetables", "Season and grill on high heat", "Cook Mexican rice", "Serve with salsa and lime"],
        image_emoji: "🌮",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 9,
        name: "Beef Burrito Bowl",
        description: "Seasoned beef with black beans, rice, and toppings",
        cuisine: "Mexican",
        prep_time: 30,
        calories: 550,
        protein: 42,
        carbs: 48,
        fat: 22,
        ingredients: ["200g ground beef", "100g black beans", "100g rice", "Cheese", "Sour cream", "Lettuce"],
        instructions: ["Brown beef with taco seasoning", "Warm black beans", "Cook cilantro lime rice", "Assemble bowl with toppings"],
        image_emoji: "🌯",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },
    {
        id: 10,
        name: "Fish Tacos",
        description: "Crispy fish with cabbage slaw and chipotle mayo",
        cuisine: "Mexican",
        prep_time: 25,
        calories: 420,
        protein: 32,
        carbs: 38,
        fat: 18,
        ingredients: ["200g white fish", "Corn tortillas", "Cabbage", "Lime", "Chipotle mayo", "Cilantro"],
        instructions: ["Season and pan-fry fish", "Shred cabbage, add lime", "Warm tortillas", "Assemble with slaw and sauce"],
        image_emoji: "🐠",
        color_from: "#14b8a6",
        color_to: "#0d9488"
    },

    // === ITALIAN ===
    {
        id: 11,
        name: "Chicken Pasta Marinara",
        description: "Grilled chicken over whole wheat pasta with tomato sauce",
        cuisine: "Italian",
        prep_time: 30,
        calories: 520,
        protein: 42,
        carbs: 55,
        fat: 14,
        ingredients: ["200g chicken breast", "150g whole wheat pasta", "200g marinara sauce", "Parmesan", "Fresh basil"],
        instructions: ["Grill seasoned chicken", "Cook pasta al dente", "Heat marinara sauce", "Combine and top with parmesan"],
        image_emoji: "🍝",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 12,
        name: "Grilled Chicken Caesar",
        description: "Classic Caesar salad with grilled chicken and croutons",
        cuisine: "Italian",
        prep_time: 20,
        calories: 420,
        protein: 40,
        carbs: 18,
        fat: 22,
        ingredients: ["200g chicken breast", "Romaine lettuce", "Caesar dressing", "Parmesan", "Croutons"],
        instructions: ["Grill chicken, slice", "Chop romaine lettuce", "Toss with dressing", "Top with chicken and parmesan"],
        image_emoji: "🥬",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    {
        id: 13,
        name: "Turkey Meatball Pasta",
        description: "Lean turkey meatballs in tomato sauce over pasta",
        cuisine: "Italian",
        prep_time: 35,
        calories: 490,
        protein: 38,
        carbs: 52,
        fat: 16,
        ingredients: ["200g ground turkey", "100g breadcrumbs", "1 egg", "Marinara sauce", "150g pasta", "Herbs"],
        instructions: ["Mix turkey with egg and breadcrumbs", "Form balls, bake 20 min", "Simmer in marinara", "Serve over pasta"],
        image_emoji: "🧆",
        color_from: "#a855f7",
        color_to: "#9333ea"
    },

    // === MIDDLE EASTERN ===
    {
        id: 14,
        name: "Chicken Shawarma Bowl",
        description: "Spiced chicken with tahini, pickles, and rice",
        cuisine: "Middle Eastern",
        prep_time: 35,
        calories: 490,
        protein: 44,
        carbs: 38,
        fat: 20,
        ingredients: ["250g chicken thigh", "Shawarma spices", "100g rice", "Tahini sauce", "Pickled vegetables", "Parsley"],
        instructions: ["Marinate chicken in spices", "Grill until charred", "Cook cumin rice", "Serve with tahini and pickles"],
        image_emoji: "🥙",
        color_from: "#a855f7",
        color_to: "#7c3aed"
    },
    {
        id: 15,
        name: "Kefta Kebabs",
        description: "Grilled spiced beef skewers with yogurt sauce",
        cuisine: "Middle Eastern",
        prep_time: 30,
        calories: 460,
        protein: 40,
        carbs: 25,
        fat: 24,
        ingredients: ["250g ground beef", "Onion", "Parsley", "Cumin, paprika", "Greek yogurt", "100g rice"],
        instructions: ["Mix beef with onion and spices", "Form onto skewers", "Grill 4 min each side", "Serve with yogurt sauce"],
        image_emoji: "🍢",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 16,
        name: "Lentil Soup",
        description: "Hearty red lentil soup with cumin and lemon",
        cuisine: "Middle Eastern",
        prep_time: 40,
        calories: 320,
        protein: 18,
        carbs: 48,
        fat: 8,
        ingredients: ["200g red lentils", "1 onion", "2 carrots", "Cumin, turmeric", "Lemon", "Olive oil"],
        instructions: ["Sauté onion and carrots", "Add lentils and water", "Simmer until soft", "Blend, serve with lemon"],
        image_emoji: "🍲",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },

    // === HIGH PROTEIN / SIMPLE ===
    {
        id: 17,
        name: "Steak & Eggs Power Plate",
        description: "Grilled steak with eggs and roasted vegetables",
        cuisine: "High Protein",
        prep_time: 20,
        calories: 580,
        protein: 52,
        carbs: 12,
        fat: 38,
        ingredients: ["200g beef steak", "3 eggs", "150g roasted vegetables", "Olive oil", "Herbs"],
        instructions: ["Season steak with salt and pepper", "Grill to preference", "Fry eggs sunny side up", "Serve with roasted vegetables"],
        image_emoji: "🥩",
        color_from: "#6366f1",
        color_to: "#4f46e5"
    },
    {
        id: 18,
        name: "Tuna Salad Wrap",
        description: "Light tuna salad in whole wheat wrap",
        cuisine: "High Protein",
        prep_time: 10,
        calories: 380,
        protein: 35,
        carbs: 30,
        fat: 14,
        ingredients: ["150g canned tuna", "Greek yogurt", "Celery", "Whole wheat wrap", "Lettuce", "Tomato"],
        instructions: ["Mix tuna with yogurt and celery", "Lay on wrap with vegetables", "Roll tightly", "Cut in half"],
        image_emoji: "🌯",
        color_from: "#0ea5e9",
        color_to: "#0284c7"
    },
    {
        id: 19,
        name: "Grilled Chicken & Sweet Potato",
        description: "Simple and clean meal prep staple",
        cuisine: "High Protein",
        prep_time: 35,
        calories: 450,
        protein: 42,
        carbs: 40,
        fat: 12,
        ingredients: ["250g chicken breast", "200g sweet potato", "Broccoli", "Olive oil", "Garlic powder"],
        instructions: ["Season chicken, grill 6 min each side", "Cube and roast sweet potato", "Steam broccoli", "Plate together"],
        image_emoji: "🍠",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 20,
        name: "Egg White Omelette",
        description: "Fluffy egg whites loaded with vegetables",
        cuisine: "High Protein",
        prep_time: 15,
        calories: 280,
        protein: 28,
        carbs: 12,
        fat: 12,
        ingredients: ["6 egg whites", "1 whole egg", "Spinach", "Mushrooms", "Cheese", "Tomatoes"],
        instructions: ["Whisk egg whites with whole egg", "Sauté vegetables", "Pour eggs, cook until set", "Fold and serve"],
        image_emoji: "🍳",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },

    // === SEAFOOD ===
    {
        id: 21,
        name: "Garlic Shrimp & Quinoa",
        description: "Succulent shrimp in garlic butter over quinoa",
        cuisine: "Seafood",
        prep_time: 25,
        calories: 420,
        protein: 36,
        carbs: 35,
        fat: 16,
        ingredients: ["250g shrimp", "150g quinoa", "Garlic", "Butter", "Lemon", "Parsley"],
        instructions: ["Cook quinoa", "Sauté garlic in butter", "Add shrimp, cook 3 min", "Finish with lemon and parsley"],
        image_emoji: "🦐",
        color_from: "#ec4899",
        color_to: "#db2777"
    },
    {
        id: 22,
        name: "Sardine Toast",
        description: "Omega-rich sardines on whole grain toast",
        cuisine: "Seafood",
        prep_time: 10,
        calories: 380,
        protein: 28,
        carbs: 32,
        fat: 18,
        ingredients: ["120g sardines", "2 slices whole grain bread", "Avocado", "Lemon", "Red onion", "Capers"],
        instructions: ["Toast bread", "Mash avocado on top", "Add sardines", "Top with onion, capers, lemon"],
        image_emoji: "🐟",
        color_from: "#0ea5e9",
        color_to: "#0284c7"
    },
    {
        id: 23,
        name: "Baked Cod with Vegetables",
        description: "Flaky white fish with roasted Mediterranean vegetables",
        cuisine: "Seafood",
        prep_time: 30,
        calories: 350,
        protein: 35,
        carbs: 22,
        fat: 14,
        ingredients: ["200g cod fillet", "Zucchini", "Bell peppers", "Cherry tomatoes", "Olive oil", "Herbs"],
        instructions: ["Season cod with herbs", "Arrange vegetables around fish", "Drizzle oil, bake 20 min at 200°C", "Serve hot"],
        image_emoji: "🐠",
        color_from: "#14b8a6",
        color_to: "#0d9488"
    },

    // === COMFORT FOOD (HEALTHIFIED) ===
    {
        id: 24,
        name: "Turkey Burger",
        description: "Lean turkey patty with all the fixings",
        cuisine: "American",
        prep_time: 20,
        calories: 420,
        protein: 38,
        carbs: 32,
        fat: 18,
        ingredients: ["200g ground turkey", "Whole wheat bun", "Lettuce", "Tomato", "Onion", "Mustard"],
        instructions: ["Form patty with seasonings", "Grill 5 min each side", "Toast bun", "Assemble with toppings"],
        image_emoji: "🍔",
        color_from: "#a855f7",
        color_to: "#9333ea"
    },
    {
        id: 25,
        name: "Chicken Quesadilla",
        description: "Crispy tortilla filled with chicken and cheese",
        cuisine: "Mexican",
        prep_time: 20,
        calories: 480,
        protein: 40,
        carbs: 38,
        fat: 20,
        ingredients: ["200g chicken", "2 tortillas", "Cheese", "Bell peppers", "Salsa", "Sour cream"],
        instructions: ["Shred cooked chicken", "Layer on tortilla with cheese", "Fold and pan-fry until crispy", "Serve with salsa"],
        image_emoji: "🧀",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },

    // More diverse meals...
    {
        id: 26,
        name: "Korean Beef Bowl",
        description: "Sweet and savory bulgogi-style beef over rice",
        cuisine: "Asian",
        prep_time: 25,
        calories: 510,
        protein: 38,
        carbs: 48,
        fat: 18,
        ingredients: ["200g beef", "Soy sauce", "Sesame oil", "Ginger", "Rice", "Green onions"],
        instructions: ["Slice beef thin", "Marinate in sauce", "Stir-fry quickly", "Serve over rice"],
        image_emoji: "🥘",
        color_from: "#dc2626",
        color_to: "#b91c1c"
    },
    {
        id: 27,
        name: "Chickpea Curry",
        description: "Creamy coconut chickpea curry with rice",
        cuisine: "Indian",
        prep_time: 30,
        calories: 420,
        protein: 16,
        carbs: 58,
        fat: 16,
        ingredients: ["200g chickpeas", "Coconut milk", "Curry paste", "Spinach", "Rice", "Cilantro"],
        instructions: ["Sauté onion and curry paste", "Add chickpeas and coconut milk", "Simmer 15 min, add spinach", "Serve over rice"],
        image_emoji: "🍛",
        color_from: "#f59e0b",
        color_to: "#d97706"
    },
    {
        id: 28,
        name: "Greek Lamb Kofta",
        description: "Spiced lamb skewers with tzatziki",
        cuisine: "Mediterranean",
        prep_time: 30,
        calories: 480,
        protein: 36,
        carbs: 28,
        fat: 26,
        ingredients: ["250g ground lamb", "Onion", "Mint", "Cumin", "Tzatziki", "Pita bread"],
        instructions: ["Mix lamb with spices and onion", "Form onto skewers", "Grill 4 min each side", "Serve with tzatziki and pita"],
        image_emoji: "🐑",
        color_from: "#8b5cf6",
        color_to: "#7c3aed"
    },
    {
        id: 29,
        name: "Vietnamese Pho",
        description: "Aromatic beef noodle soup",
        cuisine: "Asian",
        prep_time: 45,
        calories: 420,
        protein: 32,
        carbs: 48,
        fat: 12,
        ingredients: ["200g beef", "Rice noodles", "Beef broth", "Star anise", "Bean sprouts", "Herbs"],
        instructions: ["Simmer broth with spices", "Cook noodles separately", "Slice beef thin", "Assemble and pour hot broth over"],
        image_emoji: "🍜",
        color_from: "#84cc16",
        color_to: "#65a30d"
    },
    {
        id: 30,
        name: "Moroccan Chicken Tagine",
        description: "Slow-cooked chicken with olives and preserved lemon",
        cuisine: "Moroccan",
        prep_time: 50,
        calories: 460,
        protein: 40,
        carbs: 32,
        fat: 20,
        ingredients: ["300g chicken", "Olives", "Preserved lemon", "Onions", "Saffron", "Couscous"],
        instructions: ["Brown chicken pieces", "Add onions and spices", "Slow cook with olives and lemon", "Serve over couscous"],
        image_emoji: "🫕",
        color_from: "#f97316",
        color_to: "#ea580c"
    },

    // Add more variety...
    {
        id: 31,
        name: "Protein Pancakes",
        description: "Fluffy pancakes with banana and protein",
        cuisine: "Breakfast",
        prep_time: 15,
        calories: 380,
        protein: 28,
        carbs: 42,
        fat: 12,
        ingredients: ["2 eggs", "1 banana", "Oats", "Greek yogurt", "Honey", "Berries"],
        instructions: ["Blend eggs, banana, and oats", "Cook like regular pancakes", "Top with yogurt and berries"],
        image_emoji: "🥞",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },
    {
        id: 32,
        name: "Avocado Toast with Eggs",
        description: "Trendy and nutritious breakfast",
        cuisine: "Breakfast",
        prep_time: 10,
        calories: 420,
        protein: 18,
        carbs: 32,
        fat: 28,
        ingredients: ["2 eggs", "1 avocado", "Whole grain bread", "Chili flakes", "Lime", "Salt"],
        instructions: ["Toast bread", "Mash avocado with lime", "Spread on toast", "Top with poached eggs"],
        image_emoji: "🥑",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 33,
        name: "Overnight Oats",
        description: "No-cook prep-ahead breakfast",
        cuisine: "Breakfast",
        prep_time: 5,
        calories: 350,
        protein: 15,
        carbs: 52,
        fat: 10,
        ingredients: ["80g oats", "200ml milk", "Greek yogurt", "Chia seeds", "Honey", "Fruit"],
        instructions: ["Mix all ingredients", "Refrigerate overnight", "Top with fresh fruit in morning"],
        image_emoji: "🥣",
        color_from: "#a855f7",
        color_to: "#9333ea"
    },

    // Continue with more meals for variety...
    {
        id: 34,
        name: "BBQ Chicken Thighs",
        description: "Juicy grilled chicken with BBQ glaze",
        cuisine: "American",
        prep_time: 35,
        calories: 480,
        protein: 42,
        carbs: 25,
        fat: 24,
        ingredients: ["300g chicken thighs", "BBQ sauce", "Coleslaw", "Corn on cob", "Pickles"],
        instructions: ["Grill chicken, basting with BBQ sauce", "Char corn on grill", "Serve with coleslaw"],
        image_emoji: "🍗",
        color_from: "#dc2626",
        color_to: "#b91c1c"
    },
    {
        id: 35,
        name: "Stuffed Bell Peppers",
        description: "Peppers filled with beef, rice, and cheese",
        cuisine: "American",
        prep_time: 45,
        calories: 420,
        protein: 32,
        carbs: 35,
        fat: 18,
        ingredients: ["4 bell peppers", "200g ground beef", "100g rice", "Tomato sauce", "Cheese", "Onion"],
        instructions: ["Hollow out peppers", "Mix cooked beef with rice", "Stuff peppers, top with sauce and cheese", "Bake 25 min"],
        image_emoji: "🫑",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 36,
        name: "Egg Fried Rice",
        description: "Quick and satisfying rice dish",
        cuisine: "Asian",
        prep_time: 15,
        calories: 420,
        protein: 16,
        carbs: 58,
        fat: 14,
        ingredients: ["200g cooked rice", "3 eggs", "Peas", "Carrots", "Soy sauce", "Green onions"],
        instructions: ["Scramble eggs, set aside", "Stir-fry vegetables and rice", "Add eggs and soy sauce", "Garnish with green onions"],
        image_emoji: "🍚",
        color_from: "#eab308",
        color_to: "#ca8a04"
    },
    {
        id: 37,
        name: "Lamb Chops with Mint",
        description: "Pan-seared lamb with fresh mint sauce",
        cuisine: "Mediterranean",
        prep_time: 25,
        calories: 520,
        protein: 40,
        carbs: 15,
        fat: 35,
        ingredients: ["4 lamb chops", "Fresh mint", "Yogurt", "Garlic", "Roasted potatoes", "Green beans"],
        instructions: ["Season and sear lamb chops", "Make mint yogurt sauce", "Roast potatoes", "Serve together"],
        image_emoji: "🥩",
        color_from: "#8b5cf6",
        color_to: "#7c3aed"
    },
    {
        id: 38,
        name: "Spicy Tuna Poke Bowl",
        description: "Fresh raw tuna with rice and toppings",
        cuisine: "Asian",
        prep_time: 20,
        calories: 450,
        protein: 35,
        carbs: 48,
        fat: 14,
        ingredients: ["200g sushi-grade tuna", "Sushi rice", "Avocado", "Cucumber", "Sriracha mayo", "Nori"],
        instructions: ["Cube tuna, marinate in soy and sesame", "Cook sushi rice", "Arrange toppings in bowl", "Drizzle with spicy mayo"],
        image_emoji: "🍣",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 39,
        name: "Cottage Cheese Salad",
        description: "High protein refreshing salad",
        cuisine: "High Protein",
        prep_time: 10,
        calories: 280,
        protein: 28,
        carbs: 18,
        fat: 12,
        ingredients: ["200g cottage cheese", "Cherry tomatoes", "Cucumber", "Olive oil", "Fresh herbs", "Black pepper"],
        instructions: ["Chop vegetables", "Place cottage cheese in bowl", "Top with vegetables and drizzle oil"],
        image_emoji: "🧀",
        color_from: "#f8fafc",
        color_to: "#e2e8f0"
    },
    {
        id: 40,
        name: "Honey Garlic Chicken",
        description: "Sticky sweet chicken with vegetables",
        cuisine: "Asian",
        prep_time: 30,
        calories: 460,
        protein: 40,
        carbs: 38,
        fat: 16,
        ingredients: ["300g chicken thighs", "Honey", "Soy sauce", "Garlic", "Rice", "Steamed broccoli"],
        instructions: ["Make honey garlic sauce", "Cook chicken, add sauce", "Simmer until sticky", "Serve with rice and broccoli"],
        image_emoji: "🍯",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },

    // Even more variety
    {
        id: 41,
        name: "Beef Stroganoff",
        description: "Creamy beef strips over egg noodles",
        cuisine: "Russian",
        prep_time: 35,
        calories: 520,
        protein: 38,
        carbs: 42,
        fat: 24,
        ingredients: ["200g beef sirloin", "Mushro oms", "Sour cream", "Onion", "Egg noodles", "Beef broth"],
        instructions: ["Sear beef strips", "Sauté mushrooms and onion", "Add broth and sour cream", "Serve over noodles"],
        image_emoji: "🥘",
        color_from: "#78716c",
        color_to: "#57534e"
    },
    {
        id: 42,
        name: "Caprese Chicken",
        description: "Chicken topped with tomato, mozzarella, and basil",
        cuisine: "Italian",
        prep_time: 25,
        calories: 420,
        protein: 45,
        carbs: 8,
        fat: 24,
        ingredients: ["200g chicken breast", "Fresh mozzarella", "Tomatoes", "Fresh basil", "Balsamic glaze", "Olive oil"],
        instructions: ["Grill chicken", "Top with tomato and mozzarella", "Broil until cheese melts", "Drizzle balsamic and basil"],
        image_emoji: "🍅",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 43,
        name: "Harira Soup",
        description: "Traditional Moroccan lentil and chickpea soup",
        cuisine: "Moroccan",
        prep_time: 45,
        calories: 350,
        protein: 18,
        carbs: 52,
        fat: 8,
        ingredients: ["Lentils", "Chickpeas", "Tomatoes", "Celery", "Onion", "Moroccan spices", "Cilantro"],
        instructions: ["Sauté vegetables", "Add lentils, chickpeas, tomatoes", "Simmer until tender", "Finish with cilantro and lemon"],
        image_emoji: "🍲",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 44,
        name: "Spinach and Feta Stuffed Chicken",
        description: "Chicken breast stuffed with Mediterranean flavors",
        cuisine: "Mediterranean",
        prep_time: 35,
        calories: 420,
        protein: 48,
        carbs: 6,
        fat: 24,
        ingredients: ["200g chicken breast", "Spinach", "Feta cheese", "Garlic", "Sun-dried tomatoes", "Olive oil"],
        instructions: ["Cut pocket in chicken", "Mix spinach, feta, garlic", "Stuff chicken", "Bake 25 min at 200°C"],
        image_emoji: "🥗",
        color_from: "#22c55e",
        color_to: "#16a34a"
    },
    {
        id: 45,
        name: "Black Bean Tacos",
        description: "Vegetarian tacos with all the fixings",
        cuisine: "Mexican",
        prep_time: 20,
        calories: 380,
        protein: 16,
        carbs: 52,
        fat: 14,
        ingredients: ["200g black beans", "Corn tortillas", "Avocado", "Salsa", "Lime", "Cilantro"],
        instructions: ["Warm and season beans", "Warm tortillas", "Fill with beans and toppings", "Squeeze lime over"],
        image_emoji: "🌮",
        color_from: "#1e293b",
        color_to: "#0f172a"
    },
    {
        id: 46,
        name: "Lemon Herb Roast Chicken",
        description: "Whole roasted chicken with herbs",
        cuisine: "French",
        prep_time: 75,
        calories: 380,
        protein: 42,
        carbs: 4,
        fat: 22,
        ingredients: ["Whole chicken", "Lemon", "Garlic", "Rosemary", "Thyme", "Butter"],
        instructions: ["Stuff with lemon and garlic", "Rub with butter and herbs", "Roast 1 hour at 200°C", "Rest before carving"],
        image_emoji: "🍋",
        color_from: "#fbbf24",
        color_to: "#f59e0b"
    },
    {
        id: 47,
        name: "Prawn Linguine",
        description: "Garlic prawns tossed with pasta",
        cuisine: "Italian",
        prep_time: 25,
        calories: 480,
        protein: 32,
        carbs: 52,
        fat: 16,
        ingredients: ["200g prawns", "150g linguine", "Garlic", "White wine", "Chili flakes", "Parsley"],
        instructions: ["Cook pasta", "Sauté garlic and prawns", "Deglaze with wine", "Toss with pasta and herbs"],
        image_emoji: "🦐",
        color_from: "#f97316",
        color_to: "#ea580c"
    },
    {
        id: 48,
        name: "Chicken Tikka Masala",
        description: "Creamy tomato curry with tender chicken",
        cuisine: "Indian",
        prep_time: 40,
        calories: 480,
        protein: 38,
        carbs: 32,
        fat: 24,
        ingredients: ["300g chicken", "Yogurt", "Tomato sauce", "Cream", "Garam masala", "Rice"],
        instructions: ["Marinate chicken in spiced yogurt", "Grill until charred", "Simmer in tomato cream sauce", "Serve with rice"],
        image_emoji: "🍛",
        color_from: "#ef4444",
        color_to: "#dc2626"
    },
    {
        id: 49,
        name: "Beef Bibimbap",
        description: "Korean rice bowl with vegetables and egg",
        cuisine: "Asian",
        prep_time: 35,
        calories: 520,
        protein: 32,
        carbs: 58,
        fat: 18,
        ingredients: ["150g beef", "Rice", "Spinach", "Carrots", "Zucchini", "Egg", "Gochujang"],
        instructions: ["Cook rice", "Prepare and season each vegetable", "Cook beef with soy sauce", "Arrange in bowl, top with fried egg"],
        image_emoji: "🍳",
        color_from: "#dc2626",
        color_to: "#b91c1c"
    },
    {
        id: 50,
        name: "Grilled Vegetable Plate",
        description: "Colorful grilled vegetables with hummus",
        cuisine: "Mediterranean",
        prep_time: 25,
        calories: 320,
        protein: 12,
        carbs: 38,
        fat: 16,
        ingredients: ["Zucchini", "Eggplant", "Bell peppers", "Onion", "Hummus", "Olive oil"],
        instructions: ["Slice all vegetables", "Brush with oil, season", "Grill until charred", "Serve with hummus"],
        image_emoji: "🥕",
        color_from: "#84cc16",
        color_to: "#65a30d"
    }
];

// Helper function to group meals by cuisine
export function getMealsByCuisine(): Record<string, MealPlan[]> {
    return mealPlans.reduce((acc, meal) => {
        if (!acc[meal.cuisine]) {
            acc[meal.cuisine] = [];
        }
        acc[meal.cuisine].push(meal);
        return acc;
    }, {} as Record<string, MealPlan[]>);
}

// Get random meals for variety
export function getRandomMeals(count: number): MealPlan[] {
    const shuffled = [...mealPlans].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}
