#!/usr/bin/env node
/**
 * Build script to consolidate all recipe JSON files into a single TypeScript data file.
 * 
 * Usage: node scripts/build-meals.js
 * 
 * This will:
 * 1. Read all JSON files from ../recipes_sources/{healthy,cuisine,cakes-baking,ramadan}/
 * 2. Add category, subcategory, and isHealthy flags
 * 3. Generate unique IDs
 * 4. Output to src/lib/meals-data.ts
 */

const fs = require('fs');
const path = require('path');

const RECIPES_ROOT = path.join(__dirname, '..', '..', 'recipes_sources');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'lib', 'meals-data.ts');

const CATEGORIES = ['healthy', 'cuisine', 'cakes-baking', 'ramadan'];

let allMeals = [];
let idCounter = 1;

function loadJsonFile(filePath, category, subcategory) {
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        const recipes = JSON.parse(content);

        // Handle both array and object formats
        const recipeArray = Array.isArray(recipes) ? recipes : (recipes.meals || []);

        return recipeArray.map(recipe => ({
            id: idCounter++,
            ...recipe,
            // Rename 'name' to 'title' if needed (for TheMealDB format)
            title: recipe.title || recipe.strMeal || recipe.name,
            // Ensure method array exists
            method: recipe.method || recipe.instructions || [],
            // Ensure nutritional_info exists
            nutritional_info: recipe.nutritional_info || {
                kcal: String(recipe.calories || '0'),
                protein: String(recipe.protein || '0') + 'g',
                carbs: String(recipe.carbs || '0') + 'g',
                fat: String(recipe.fat || '0') + 'g',
                fibre: '0g',
                sugars: '0g',
                salt: '0g',
                saturates: '0g'
            },
            // Category info
            category: category,
            subcategory: subcategory,
            isHealthy: category === 'healthy',
            // Image paths
            local_image_path: recipe.local_image_path || '',
            image_url: recipe.image_url || recipe.strMealThumb || ''
        }));
    } catch (err) {
        console.error(`Error loading ${filePath}:`, err.message);
        return [];
    }
}

function processCategory(category) {
    const categoryPath = path.join(RECIPES_ROOT, category);

    if (!fs.existsSync(categoryPath)) {
        console.log(`Skipping ${category} - folder not found`);
        return;
    }

    const files = fs.readdirSync(categoryPath).filter(f => f.endsWith('.json'));
    console.log(`Processing ${category}: ${files.length} files`);

    files.forEach(file => {
        const subcategory = file.replace('.json', '');
        const filePath = path.join(categoryPath, file);
        const meals = loadJsonFile(filePath, category, subcategory);
        allMeals = allMeals.concat(meals);
        console.log(`  - ${file}: ${meals.length} recipes`);
    });
}

function generateOutput() {
    const output = `// Auto-generated file - DO NOT EDIT DIRECTLY
// Generated by scripts/build-meals.js
// Total: ${allMeals.length} recipes

import { MealPlan } from './types';

export const allMeals: MealPlan[] = ${JSON.stringify(allMeals, null, 2)};

// Export by category for convenience
export const healthyMeals = allMeals.filter(m => m.isHealthy);
export const cuisineMeals = allMeals.filter(m => m.category === 'cuisine');
export const dessertMeals = allMeals.filter(m => m.category === 'cakes-baking');
export const ramadanMeals = allMeals.filter(m => m.category === 'ramadan');

// Stats
export const mealStats = {
    total: ${allMeals.length},
    healthy: healthyMeals.length,
    cuisine: cuisineMeals.length,
    desserts: dessertMeals.length,
    ramadan: ramadanMeals.length
};
`;

    fs.writeFileSync(OUTPUT_FILE, output, 'utf8');
    console.log(`\n✅ Generated ${OUTPUT_FILE}`);
    console.log(`   Total recipes: ${allMeals.length}`);
}

// Main execution
console.log('🍽️  Building meals database...\n');

CATEGORIES.forEach(processCategory);

// Also process the main recipes.json if it exists
const mainRecipesPath = path.join(RECIPES_ROOT, 'recipes.json');
if (fs.existsSync(mainRecipesPath)) {
    console.log('\nProcessing main recipes.json...');
    const meals = loadJsonFile(mainRecipesPath, 'international', 'themealdb');
    allMeals = allMeals.concat(meals);
    console.log(`  - recipes.json: ${meals.length} recipes`);
}

generateOutput();

console.log('\n📊 Summary:');
const categoryCounts = {};
allMeals.forEach(m => {
    categoryCounts[m.category] = (categoryCounts[m.category] || 0) + 1;
});
Object.entries(categoryCounts).forEach(([cat, count]) => {
    console.log(`   ${cat}: ${count} recipes`);
});
